"""create_tables

Revision ID: 43b6b4edfcbf
Revises: 
Create Date: 2026-09-29 05:25:05.890295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b6b4edfcbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_otps_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_otps_phone'), ['phone'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('default_address', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_order_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=True)

    op.create_table('outlets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('tax_rate_percent', sa.Integer(), nullable=True),
    sa.Column('opening_hours', sa.String(length=100), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('gstin', sa.String(length=30), nullable=True),
    sa.Column('fssai_license_number', sa.String(length=30), nullable=True),
    sa.Column('upi_vpa', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outlets_id'), ['id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_te', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outlet_id', 'name', name='uq_category_outlet_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('min_order_paise', sa.Integer(), nullable=True),
    sa.Column('max_discount_paise', sa.Integer(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_coupons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupons_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('customer_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('address_line', sa.Text(), nullable=False),
    sa.Column('landmark', sa.String(length=150), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_addresses_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_addresses_id'), ['id'], unique=False)

    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('qr_code_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('active_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outlet_id', 'label', name='uq_table_outlet_label')
    )
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tables_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tables_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('cashier_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=False),
    sa.Column('cashier_name', sa.String(length=100), nullable=False),
    sa.Column('shift_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('opening_float_paise', sa.Integer(), nullable=True),
    sa.Column('cash_sales_paise', sa.Integer(), nullable=True),
    sa.Column('upi_sales_paise', sa.Integer(), nullable=True),
    sa.Column('card_sales_paise', sa.Integer(), nullable=True),
    sa.Column('petty_cash_in_paise', sa.Integer(), nullable=True),
    sa.Column('petty_cash_out_paise', sa.Integer(), nullable=True),
    sa.Column('expected_cash_paise', sa.Integer(), nullable=True),
    sa.Column('actual_cash_paise', sa.Integer(), nullable=True),
    sa.Column('difference_paise', sa.Integer(), nullable=True),
    sa.Column('denominations_json', sa.Text(), nullable=True),
    sa.Column('closing_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashier_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cashier_shifts_cashier_id'), ['cashier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cashier_shifts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cashier_shifts_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cashier_shifts_status'), ['status'], unique=False)

    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_te', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_te', sa.Text(), nullable=True),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_veg', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('has_variants', sa.Boolean(), nullable=True),
    sa.Column('track_stock', sa.Boolean(), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('is_special', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_items_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('delivery_status', sa.String(length=30), nullable=True),
    sa.Column('delivery_fee_paise', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('subtotal_paise', sa.Integer(), nullable=True),
    sa.Column('tax_paise', sa.Integer(), nullable=True),
    sa.Column('discount_paise', sa.Integer(), nullable=True),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('total_paise', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_customer_phone'), ['customer_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_order_type'), ['order_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_table_id'), ['table_id'], unique=False)

    op.create_table('service_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('call_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_calls_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_calls_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_calls_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_calls_table_id'), ['table_id'], unique=False)

    op.create_table('table_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('reservation_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_email', sa.String(length=100), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.String(length=20), nullable=False),
    sa.Column('reservation_time', sa.String(length=20), nullable=False),
    sa.Column('seating_preference', sa.String(length=50), nullable=True),
    sa.Column('occasion', sa.String(length=50), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_reservations_customer_phone'), ['customer_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_reservations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_reservations_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_reservations_reservation_date'), ['reservation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_reservations_reservation_number'), ['reservation_number'], unique=True)

    op.create_table('menu_item_addons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_te', sa.String(length=100), nullable=True),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_item_addons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_item_addons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_item_addons_item_id'), ['item_id'], unique=False)

    op.create_table('menu_item_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_te', sa.String(length=100), nullable=True),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_item_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_item_variants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_item_variants_item_id'), ['item_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('variant_name', sa.String(length=100), nullable=True),
    sa.Column('selected_addons_json', sa.Text(), nullable=True),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('unit_price_paise', sa.Integer(), nullable=False),
    sa.Column('total_price_paise', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('txn_id', sa.String(length=100), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_paid_at'), ['paid_at'], unique=False)

    op.create_table('stock_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('change_qty', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_logs_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_logs_outlet_id'), ['outlet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_logs_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_stock_logs_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_logs_id'))
        batch_op.drop_index(batch_op.f('ix_stock_logs_created_at'))

    op.drop_table('stock_logs')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_paid_at'))
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('menu_item_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_item_variants_item_id'))
        batch_op.drop_index(batch_op.f('ix_menu_item_variants_id'))

    op.drop_table('menu_item_variants')
    with op.batch_alter_table('menu_item_addons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_item_addons_item_id'))
        batch_op.drop_index(batch_op.f('ix_menu_item_addons_id'))

    op.drop_table('menu_item_addons')
    with op.batch_alter_table('table_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_reservations_reservation_number'))
        batch_op.drop_index(batch_op.f('ix_table_reservations_reservation_date'))
        batch_op.drop_index(batch_op.f('ix_table_reservations_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_table_reservations_id'))
        batch_op.drop_index(batch_op.f('ix_table_reservations_customer_phone'))

    op.drop_table('table_reservations')
    with op.batch_alter_table('service_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_calls_table_id'))
        batch_op.drop_index(batch_op.f('ix_service_calls_status'))
        batch_op.drop_index(batch_op.f('ix_service_calls_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_service_calls_id'))

    op.drop_table('service_calls')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_table_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_orders_order_type'))
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_orders_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_orders_id'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_phone'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))

    op.drop_table('orders')
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_items_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_menu_items_id'))
        batch_op.drop_index(batch_op.f('ix_menu_items_category_id'))

    op.drop_table('menu_items')
    with op.batch_alter_table('cashier_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cashier_shifts_status'))
        batch_op.drop_index(batch_op.f('ix_cashier_shifts_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_cashier_shifts_id'))
        batch_op.drop_index(batch_op.f('ix_cashier_shifts_cashier_id'))

    op.drop_table('cashier_shifts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tables_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_tables_id'))

    op.drop_table('tables')
    with op.batch_alter_table('customer_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_addresses_id'))
        batch_op.drop_index(batch_op.f('ix_customer_addresses_customer_id'))

    op.drop_table('customer_addresses')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_coupons_id'))
        batch_op.drop_index(batch_op.f('ix_coupons_code'))

    op.drop_table('coupons')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outlets_id'))

    op.drop_table('outlets')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))

    op.drop_table('customers')
    with op.batch_alter_table('customer_otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_otps_phone'))
        batch_op.drop_index(batch_op.f('ix_customer_otps_id'))

    op.drop_table('customer_otps')
    # ### end Alembic commands ###
