"""
Complete Arabieq Restaurant Menu Dataset transcribed from the 15-page Menu PDF.
"""

CATEGORIES = [
    {
        "id": 1,
        "name": "Tiffin & Breakfast",
        "name_te": "టిఫిన్ & బ్రేక్‌ఫాస్ట్",
        "icon": "Coffee",
        "sort_order": 1,
        "is_active": True,
        "image_url": "/dishes/3d_tiffin.jpg",
    },
    {
        "id": 2,
        "name": "Dosa & Uttapam Specials",
        "name_te": "దోశ & ఊతప్పం స్పెషల్స్",
        "icon": "Utensils",
        "sort_order": 2,
        "is_active": True,
        "image_url": "/dishes/3d_dosa.jpg",
    },
    {
        "id": 3,
        "name": "Snacks & Sweets",
        "name_te": "స్నాక్స్ & స్వీట్స్",
        "icon": "Sparkles",
        "sort_order": 3,
        "is_active": True,
        "image_url": "/dishes/3d_sweets.jpg",
    },
    {
        "id": 4,
        "name": "Soups & Salads",
        "name_te": "సూప్‌లు & సలాడ్లు",
        "icon": "Soup",
        "sort_order": 4,
        "is_active": True,
        "image_url": "/dishes/3d_veg_starters.jpg",
    },
    {
        "id": 5,
        "name": "Veg Starters",
        "name_te": "వెజ్ స్టార్టర్స్",
        "icon": "Salad",
        "sort_order": 5,
        "is_active": True,
        "image_url": "/dishes/3d_veg_starters.jpg",
    },
    {
        "id": 6,
        "name": "Non-Veg Starters",
        "name_te": "నాన్-వెజ్ స్టార్టర్స్",
        "icon": "Flame",
        "sort_order": 6,
        "is_active": True,
        "image_url": "/dishes/3d_nonveg_starters.jpg",
    },
    {
        "id": 7,
        "name": "Indian Breads",
        "name_te": "రొట్టెలు & నాన్స్",
        "icon": "CircleDot",
        "sort_order": 7,
        "is_active": True,
        "image_url": "/dishes/3d_curries.jpg",
    },
    {
        "id": 8,
        "name": "Biryani & Pulavs",
        "name_te": "బిర్యానీ & పులావ్‌లు",
        "icon": "Flame",
        "sort_order": 8,
        "is_active": True,
        "image_url": "/dishes/3d_biryani.jpg",
    },
    {
        "id": 9,
        "name": "Curries & Main Course",
        "name_te": "కూరలు & మెయిన్ కోర్స్",
        "icon": "UtensilsCrossed",
        "sort_order": 9,
        "is_active": True,
        "image_url": "/dishes/3d_curries.jpg",
    },
    {
        "id": 10,
        "name": "Arabian Mandi & Al-Faham",
        "name_te": "అరేబియన్ మండి & అల్-ఫహమ్",
        "icon": "Crown",
        "sort_order": 10,
        "is_active": True,
        "image_url": "/dishes/3d_mandi.jpg",
    },
    {
        "id": 11,
        "name": "Beverages, Shakes & Desserts",
        "name_te": "కూల్ డ్రింక్స్, షేక్స్ & డెజర్ట్స్",
        "icon": "Wine",
        "sort_order": 11,
        "is_active": True,
        "image_url": "/dishes/3d_shawarma.jpg",
    },
]

ITEMS = [
    # 1. Tiffin & Breakfast (Page 2)
    {"cat": 1, "name": "Idly (2 Pcs)", "name_te": "ఇడ్లీ (2)", "price": 30, "veg": True, "desc": "Soft and fluffy steamed rice cakes served with sambar & chutneys", "img": "/dishes/idly_plate.jpg"},
    {"cat": 1, "name": "Idly (2) Vada (1)", "name_te": "ఇడ్లీ (2) వడ (1)", "price": 50, "veg": True, "desc": "Classic combination of 2 steamed idlies and 1 crispy medu vada", "img": "/dishes/idly_vada_combo.jpg"},
    {"cat": 1, "name": "Idly (1) Vada (1)", "name_te": "ఇడ్లీ (1) వడ (1)", "price": 40, "veg": True, "desc": "1 steamed idly and 1 crispy medu vada with hot sambar", "img": "/dishes/idly_vada_combo.jpg"},
    {"cat": 1, "name": "Medu Vada (1 Pc)", "name_te": "వడ (1)", "price": 20, "veg": True, "desc": "Golden fried crispy urad dal doughnut with ginger & curry leaves", "img": "/dishes/medu_vada.jpg"},
    {"cat": 1, "name": "Button Idly (Mini Sambar Idly)", "name_te": "బటన్ ఇడ్లీ", "price": 50, "veg": True, "desc": "Bite-sized mini idlies immersed in piping hot aromatic ghee sambar", "img": "/dishes/button_idly.jpg"},
    {"cat": 1, "name": "Ghee Podi Idly (2 Pcs)", "name_te": "నెయ్యి కారప్పొడి ఇడ్లీ (2)", "price": 60, "veg": True, "desc": "Steamed idlies tossed in desi cow ghee and authentic gun powder podi", "img": "/dishes/ghee_podi_idly.jpg"},
    {"cat": 1, "name": "Tava Idly (2 Pcs)", "name_te": "తవా ఇడ్లీ (2)", "price": 60, "veg": True, "desc": "Pan-tossed spicy masala idly with onions, capsicum & herbs", "img": "/dishes/ghee_podi_idly.jpg"},
    {"cat": 1, "name": "Poori Saagu (2 Pcs)", "name_te": "పూరీ సాగు (2)", "price": 50, "veg": True, "desc": "Puffed whole wheat pooris served with traditional spiced vegetable saagu", "img": "/dishes/poori_saagu.jpg"},
    {"cat": 1, "name": "Poori Kurma (2 Pcs)", "name_te": "పూరీ కుర్మా (2)", "price": 50, "veg": True, "desc": "Crispy golden pooris served with coconut vegetable kurma", "img": "/dishes/poori_saagu.jpg"},
    {"cat": 1, "name": "Curd Vada (Dahi Vada)", "name_te": "పెరుగు వడ (1)", "price": 40, "veg": True, "desc": "Crispy medu vada soaked in tempered chilled yogurt with tadka", "img": "/dishes/medu_vada.jpg"},
    {"cat": 1, "name": "Mysore Bonda (4 Pcs)", "name_te": "మైసూర్ బోండా", "price": 40, "veg": True, "desc": "Fluffy golden crisp batter dumplings served with coconut chutney", "img": "/dishes/mysore_bonda.jpg"},
    {"cat": 1, "name": "Bonda Special", "name_te": "బోండా", "price": 40, "veg": True, "desc": "Crispy hot bondas with allam (ginger) chutney & sambar", "img": "/dishes/mysore_bonda.jpg"},
    {"cat": 1, "name": "Jeedipappu Upma (Cashew Upma)", "name_te": "జీడిపప్పు ఉప్మా", "price": 60, "veg": True, "desc": "Semolina upma roasted with roasted cashews, ginger & ghee", "img": "/dishes/kesari_bath.jpg"},
    {"cat": 1, "name": "Ghee Pongal", "name_te": "పొంగల్", "price": 60, "veg": True, "desc": "Traditional rice and moong dal khichdi tempered with pepper, cumin, cashews & pure ghee", "img": "/dishes/ghee_pongal.jpg"},
    {"cat": 1, "name": "Tomato Bath", "name_te": "టొమాటో బాత్", "price": 60, "veg": True, "desc": "Tangy and aromatic spiced tomato semolina bath", "img": "/dishes/ghee_pongal.jpg"},
    {"cat": 1, "name": "Lemon Rice", "name_te": "లెమన్ రైస్", "price": 60, "veg": True, "desc": "Fragrant steamed rice tempered with lemon juice, mustard, peanuts & green chillies", "img": "/dishes/ghee_pongal.jpg"},
    {"cat": 1, "name": "Tomato Rice", "name_te": "టొమాటో రైస్", "price": 60, "veg": True, "desc": "Flavored basmati rice cooked with fresh ripe tomatoes and spices", "img": "/dishes/ghee_pongal.jpg"},
    {"cat": 1, "name": "Curd Rice (Bagala Bath)", "name_te": "పెరుగు అన్నం", "price": 60, "veg": True, "desc": "Creamy tempered yogurt rice topped with pomegranate and mustard tadka", "img": "/dishes/curd.jpg"},
    {"cat": 1, "name": "Bisibele Bath", "name_te": "బిసిబేలే బాత్", "price": 60, "veg": True, "desc": "Authentic Karnataka style lentil rice stew with ghee and boondi topping", "img": "/dishes/ghee_pongal.jpg"},

    # 2. Dosa & Uttapam Special (Page 3)
    {"cat": 2, "name": "Plain Dosa", "name_te": "ప్లెయిన్ దోశ", "price": 35, "veg": True, "desc": "Crispy golden crepe made of fermented lentil and rice batter", "img": "/dishes/3d_dosa.jpg"},
    {"cat": 2, "name": "Masala Dosa", "name_te": "మసాలా దోశ", "price": 45, "veg": True, "desc": "Crispy dosa stuffed with spiced potato masala", "img": "/dishes/masala_dosa.jpg"},
    {"cat": 2, "name": "Onion Dosa", "name_te": "ఆనియన్ దోశ", "price": 50, "veg": True, "desc": "Crispy dosa generously sprinkled with finely chopped onions & green chillies", "img": "/dishes/onion_uttapam.jpg"},
    {"cat": 2, "name": "Set Dosa (3 Pcs)", "name_te": "సెట్ దోశ (3)", "price": 60, "veg": True, "desc": "Soft, spongy thick dosas served in a set of 3 with creamy saagu", "img": "/dishes/3d_dosa.jpg"},
    {"cat": 2, "name": "Pepper Plain Dosa", "name_te": "పెప్పర్ ప్లెయిన్ దోశ", "price": 50, "veg": True, "desc": "Crispy dosa seasoned with crushed black pepper & ghee", "img": "/dishes/3d_dosa.jpg"},
    {"cat": 2, "name": "Pepper Masala Dosa", "name_te": "పెప్పర్ మసాలా దోశ", "price": 70, "veg": True, "desc": "Pepper spiced potato masala rolled in crispy golden dosa", "img": "/dishes/masala_dosa.jpg"},
    {"cat": 2, "name": "Butter Plain Dosa", "name_te": "బట్టర్ ప్లెయిన్ దోశ", "price": 50, "veg": True, "desc": "Crispy dosa roasted with dollops of fresh butter", "img": "/dishes/3d_dosa.jpg"},
    {"cat": 2, "name": "Butter Masala Dosa", "name_te": "బట్టర్ మసాలా దోశ", "price": 70, "veg": True, "desc": "Classic aloo masala dosa enriched with melting butter", "img": "/dishes/masala_dosa.jpg"},
    {"cat": 2, "name": "Cheese Plain Dosa", "name_te": "చీజ్ ప్లెయిన్ దోశ", "price": 60, "veg": True, "desc": "Crispy dosa loaded with melted mozzarella & cheddar cheese", "img": "/dishes/3d_dosa.jpg"},
    {"cat": 2, "name": "Cheese Masala Dosa", "name_te": "చీజ్ మసాలా దోశ", "price": 70, "veg": True, "desc": "Spiced potato masala dosa topped with melted cheese", "img": "/dishes/masala_dosa.jpg"},
    {"cat": 2, "name": "Ghee Podi Plain Dosa", "name_te": "నెయ్యి కారప్పొడి దోశ", "price": 50, "veg": True, "desc": "Crispy dosa smeared with spiced gun powder and aromatic ghee", "img": "/dishes/ghee_podi_idly.jpg"},
    {"cat": 2, "name": "Ghee Podi Masala Dosa", "name_te": "నెయ్యి కారప్పొడి మసాలా దోశ", "price": 80, "veg": True, "desc": "Karam podi coated dosa stuffed with rich potato masala", "img": "/dishes/masala_dosa.jpg"},
    {"cat": 2, "name": "Rava Dosa", "name_te": "రవ్వ దోశ", "price": 60, "veg": True, "desc": "Crispy lattice-style semolina crepe with cumin and peppercorns", "img": "/dishes/rava_dosa.jpg"},
    {"cat": 2, "name": "Rava Masala Dosa", "name_te": "రవ్వ మసాలా దోశ", "price": 70, "veg": True, "desc": "Crispy rava dosa filled with flavorful spiced aloo masala", "img": "/dishes/rava_dosa.jpg"},
    {"cat": 2, "name": "Rava Onion Dosa", "name_te": "రవ్వ ఆనియన్ దోశ", "price": 70, "veg": True, "desc": "Semolina dosa studded with golden browned onions and green chillies", "img": "/dishes/rava_dosa.jpg"},
    {"cat": 2, "name": "Mysore Masala Dosa", "name_te": "మైసూర్ మసాలా దోశ", "price": 60, "veg": True, "desc": "Dosa layered with spicy red garlic chutney and aloo bhaji", "img": "/dishes/masala_dosa.jpg"},
    {"cat": 2, "name": "Paneer Dosa", "name_te": "పన్నీర్ దోశ", "price": 80, "veg": True, "desc": "Dosa filled with grated spiced fresh cottage cheese", "img": "/dishes/masala_dosa.jpg"},
    {"cat": 2, "name": "Paneer Cheese Dosa", "name_te": "పన్నీర్ చీజ్ దోశ", "price": 90, "veg": True, "desc": "Decadent combination of spiced paneer and melted cheese", "img": "/dishes/masala_dosa.jpg"},
    {"cat": 2, "name": "Onion Uttapam", "name_te": "ఆనియన్ ఊతప్పం", "price": 60, "veg": True, "desc": "Thick spongy pancake topped with caramelized chopped onions", "img": "/dishes/onion_uttapam.jpg"},
    {"cat": 2, "name": "Tomato Uttapam", "name_te": "టొమాటో ఊతప్పం", "price": 60, "veg": True, "desc": "Thick rice crepe studded with fresh juicy diced tomatoes", "img": "/dishes/onion_uttapam.jpg"},
    {"cat": 2, "name": "Ragi Dosa", "name_te": "రాగి దోశ", "price": 60, "veg": True, "desc": "Nutritious finger millet crepe roasted to perfection", "img": "/dishes/3d_dosa.jpg"},
    {"cat": 2, "name": "Upma Pesarattu (MLA Pesarattu)", "name_te": "ఉప్మా పెసరట్టు", "price": 70, "veg": True, "desc": "Green gram moong dal dosa stuffed with hot ginger rava upma", "img": "/dishes/rava_dosa.jpg"},
    {"cat": 2, "name": "Plain Pesarattu", "name_te": "ప్లెయిన్ పెసరట్టు", "price": 50, "veg": True, "desc": "Traditional Andhra green gram crepe served with ginger allam chutney", "img": "/dishes/rava_dosa.jpg"},

    # 3. Snacks & Sweets (Page 3)
    {"cat": 3, "name": "Punugulu", "name_te": "పునుగులు", "price": 30, "veg": True, "desc": "Deep fried crispy bite-sized street fritters with spicy tomato chutney", "img": "/dishes/punugulu.jpg"},
    {"cat": 3, "name": "Onion Pakoda", "name_te": "ఆనియన్ పకోడ", "price": 50, "veg": True, "desc": "Crunchy gram flour batter-fried sliced onion fritters", "img": "/dishes/onion_pakoda.jpg"},
    {"cat": 3, "name": "Palak Pakoda", "name_te": "పాలక్ పకోడ", "price": 60, "veg": True, "desc": "Crispy fresh spinach leaves fried in seasoned besan batter", "img": "/dishes/palak_pakoda.jpg"},
    {"cat": 3, "name": "Mirchi Bajji (4 Pcs)", "name_te": "మిర్చి బజ్జి", "price": 40, "veg": True, "desc": "Stuffed green chillies batter fried and topped with spiced onions and lemon", "img": "/dishes/mirchi_bajji.jpg"},
    {"cat": 3, "name": "Masala Vada (Dal Vada)", "name_te": "మసాలా వడ", "price": 40, "veg": True, "desc": "Crunchy chana dal patties infused with onions, coriander and fennel", "img": "/dishes/masala_vada.jpg"},
    {"cat": 3, "name": "Nellore Vada (4 Pcs)", "name_te": "నెల్లూరు వడ (4)", "price": 40, "veg": True, "desc": "Authentic coastal Nellore style crispy fried vadas", "img": "/dishes/nellore_vada.jpg"},
    {"cat": 3, "name": "Kesari Bath (Sheera)", "name_te": "కేసరి బాత్", "price": 50, "veg": True, "desc": "Melt-in-mouth saffron semolina pudding with ghee and cashews", "img": "/dishes/kesari_bath.jpg"},
    {"cat": 3, "name": "Gulab Jamun (2 Pcs)", "name_te": "గులాబ్ జామూన్", "price": 40, "veg": True, "desc": "Soft khoya dumplings dipped in rose flavored cardamom sugar syrup", "img": "/dishes/gulab_jamun.jpg"},
    {"cat": 3, "name": "Kala Jamun", "name_te": "కాలా జామూన్", "price": 40, "veg": True, "desc": "Dark roasted caramelized gulab jamuns with rich khoya center", "img": "/dishes/kala_jamun.jpg"},
    {"cat": 3, "name": "Double Ka Meetha", "name_te": "డబల్ కా మీఠా", "price": 50, "veg": True, "desc": "Hyderabadi royal fried bread dessert soaked in saffron rabri and nuts", "img": "/dishes/double_ka_meetha.jpg"},
    {"cat": 3, "name": "Gajar Ka Halwa", "name_te": "గాజర్ కా హల్వా", "price": 60, "veg": True, "desc": "Slow-cooked fresh red carrots with mawa, pure ghee, and dry fruits", "img": "/dishes/gajar_ka_halwa.jpg"},
    {"cat": 3, "name": "Kaddu Ka Kheer", "name_te": "కద్దూ కి ఖీర్", "price": 60, "veg": True, "desc": "Nawabi bottle gourd pudding simmered with milk, sago pearls and cardamom", "img": "/dishes/kaddu_ka_kheer.jpg"},
    {"cat": 3, "name": "Qubani Ka Meetha", "name_te": "ఖుబానీ కా మీఠా", "price": 60, "veg": True, "desc": "Authentic Hyderabadi stewed apricot compote with custard cream", "img": "/dishes/qubani_ka_meetha.jpg"},

    # 4. Soups & Salads (Page 4 & 5)
    {"cat": 4, "name": "Veg Sweet Corn Soup", "name_te": "వెజ్ స్వీట్ కార్న్ సూప్", "price": 90, "veg": True, "desc": "Comforting creamy soup with sweet golden corn kernels and veggies", "img": "/dishes/veg_sweet_corn_soup.jpg"},
    {"cat": 4, "name": "Veg Manchow Soup", "name_te": "వెజ్ మాంచో సూప్", "price": 90, "veg": True, "desc": "Spicy Indo-Chinese broth garnished with crispy fried noodles", "img": "/dishes/veg_manchow_soup.jpg"},
    {"cat": 4, "name": "Veg Hot & Sour Soup", "name_te": "వెజ్ హాట్ & సోర్ సూప్", "price": 90, "veg": True, "desc": "Zesty spicy and tangy Chinese vegetable broth", "img": "/dishes/veg_hot_sour_soup.jpg"},
    {"cat": 4, "name": "Chicken Sweet Corn Soup", "name_te": "చికెన్ స్వీట్ కార్న్ సూప్", "price": 100, "veg": False, "desc": "Tender shredded chicken and sweet corn in savory egg drop broth", "img": "/dishes/chicken_sweet_corn_soup.jpg"},
    {"cat": 4, "name": "Chicken Manchow Soup", "name_te": "చికెన్ మాంచో సూప్", "price": 100, "veg": False, "desc": "Spicy chicken soup infused with garlic, chilli and crispy noodle crunch", "img": "/dishes/chicken_manchow_soup.jpg"},
    {"cat": 4, "name": "Chicken Hot & Sour Soup", "name_te": "చికెన్ హాట్ & సోర్ సూప్", "price": 100, "veg": False, "desc": "Tangy and fiery chicken soup with mushrooms and bamboo shoots", "img": "/dishes/chicken_hot_sour_soup.jpg"},
    {"cat": 4, "name": "Mutton Miriyala Soup", "name_te": "మటన్ మిరియాల సూప్", "price": 150, "veg": False, "desc": "Traditional South Indian spicy black pepper mutton bone soup", "img": "/dishes/mutton_miriyala_soup.jpg"},
    {"cat": 4, "name": "Mutton Maraq Soup", "name_te": "మటన్ మరాఖ్ సూప్", "price": 150, "veg": False, "desc": "Authentic Arabian slow-cooked bone broth simmered with mild spices and herbs", "img": "/dishes/mutton_maraq_soup.jpg"},
    {"cat": 4, "name": "Mutton Shorba Soup", "name_te": "మటన్ షోర్బా", "price": 150, "veg": False, "desc": "Rich and nourishing Mughlai mutton broth flavored with saffron and mint", "img": "/dishes/mutton_shorba_soup.jpg"},
    {"cat": 4, "name": "Fresh Green Salad", "name_te": "గ్రీన్ సలాడ్", "price": 60, "veg": True, "desc": "Sliced cucumbers, tomatoes, carrots, onions with lemon wedges", "img": "/dishes/fresh_green_salad.jpg"},
    {"cat": 4, "name": "Masala Papad", "name_te": "మసాలా పాపడ్", "price": 50, "veg": True, "desc": "Roasted lentil wafer topped with seasoned onions, tomatoes and sev", "img": "/dishes/masala_papad.jpg"},
    {"cat": 4, "name": "Crispy French Fries", "name_te": "ఫ్రెంచ్ ఫ్రైస్", "price": 80, "veg": True, "desc": "Golden fried salted potato batons with ketchup", "img": "/dishes/3d_veg_starters.jpg"},

    # 5. Veg Starters (Page 5)
    {"cat": 5, "name": "Veg Manchurian Dry", "name_te": "వెజ్ మంచూరియన్", "price": 90, "veg": True, "desc": "Crispy vegetable balls tossed in spicy soy-garlic Manchurian glaze", "img": "/dishes/veg_manchurian.jpg"},
    {"cat": 5, "name": "Veg 65", "name_te": "వెజ్ 65", "price": 90, "veg": True, "desc": "Spicy batter-fried mixed vegetable bites with curry leaves and yogurt sauce", "img": "/dishes/gobi_65.jpg"},
    {"cat": 5, "name": "Veg Crispy", "name_te": "వెజ్ క్రిస్పీ", "price": 90, "veg": True, "desc": "Batter-fried julienne vegetables tossed in sweet and spicy schezwan sauce", "img": "/dishes/veg_spring_rolls.jpg"},
    {"cat": 5, "name": "Arabeiq Special Veg Stick", "name_te": "అరబిక్ స్పెషల్ వెజ్ స్టిక్", "price": 80, "veg": True, "desc": "Chef special skewered vegetable kebabs with Arabian herb seasoning", "img": "/dishes/paneer_65.jpg"},
    {"cat": 5, "name": "Paneer Chilly Dry", "name_te": "పన్నీర్ చిల్లీ", "price": 250, "veg": True, "desc": "Fresh cottage cheese cubes tossed with capsicum, onions and green chillies", "img": "/dishes/chilly_paneer.jpg"},
    {"cat": 5, "name": "Paneer 65", "name_te": "పన్నీర్ 65", "price": 250, "veg": True, "desc": "Golden fried paneer chunks tossed with curd, curry leaves and red chilli sauce", "img": "/dishes/paneer_65.jpg"},
    {"cat": 5, "name": "Paneer Majestic", "name_te": "పన్నీర్ మెజెస్టిక్", "price": 250, "veg": True, "desc": "Strips of paneer sauteed in a creamy mint and green chilli yogurt sauce", "img": "/dishes/paneer_65.jpg"},
    {"cat": 5, "name": "Dragon Paneer", "name_te": "డ్రాగన్ పన్నీర్", "price": 250, "veg": True, "desc": "Crispy paneer fingers in a fiery red dragon chilli sauce with cashews", "img": "/dishes/chilly_paneer.jpg"},
    {"cat": 5, "name": "Mushroom 65", "name_te": "మష్రూమ్ 65", "price": 220, "veg": True, "desc": "Crispy battered button mushrooms tossed in spicy 65 masala", "img": "/dishes/mushroom_65.jpg"},
    {"cat": 5, "name": "Mushroom Manchurian", "name_te": "మష్రూమ్ మంచూరియన్", "price": 220, "veg": True, "desc": "Button mushrooms tossed in savory Indo-Chinese garlic sauce", "img": "/dishes/mushroom_65.jpg"},
    {"cat": 5, "name": "Baby Corn Manchurian", "name_te": "బేబీ కార్న్ మంచూరియన్", "price": 200, "veg": True, "desc": "Crispy fried baby corn in spicy garlic soy sauce", "img": "/dishes/babycorn_65.jpg"},
    {"cat": 5, "name": "Crispy Corn Salt & Pepper", "name_te": "క్రిస్పీ కార్న్ సాల్ట్ & పెప్పర్", "price": 220, "veg": True, "desc": "Fried sweet corn tossed with freshly cracked black pepper, onions and herbs", "img": "/dishes/babycorn_65.jpg"},
    {"cat": 5, "name": "Gobi 65", "name_te": "గోబీ 65", "price": 200, "veg": True, "desc": "Spicy and crunchy cauliflower florets tossed with curry leaves", "img": "/dishes/gobi_65.jpg"},
    {"cat": 5, "name": "Gobi Manchurian Dry", "name_te": "గోబీ మంచూరియన్", "price": 170, "veg": True, "desc": "Deep-fried cauliflower florets in spicy tangy Manchurian sauce", "img": "/dishes/gobi_manchurian.jpg"},

    # 6. Non-Veg Starters (Chicken, Mutton, Fish, Prawns, Egg, Natu Kodi) (Page 6)
    {"cat": 6, "name": "Chilly Chicken Dry", "name_te": "చిల్లీ చికెన్", "price": 250, "veg": False, "desc": "Boneless chicken tossed with green chillies, bell peppers and soy sauce", "img": "/dishes/chilly_chicken_dry.jpg"},
    {"cat": 6, "name": "Chicken 65", "name_te": "చికెన్ 65", "price": 260, "veg": False, "desc": "Classic spicy deep-fried chicken cubes with curd, curry leaves & spices", "img": "/dishes/chicken_65.jpg"},
    {"cat": 6, "name": "Chicken Majestic", "name_te": "చికెన్ మెజెస్టిక్", "price": 270, "veg": False, "desc": "Hyderabadi style fried chicken strips coated in spicy yogurt mint sauce", "img": "/dishes/chicken_majestic.jpg"},
    {"cat": 6, "name": "Chicken Lollipop (6 Pcs)", "name_te": "చికెన్ లాలీపాప్", "price": 250, "veg": False, "desc": "Crispy chicken winglets tossed in fiery schezwan garlic sauce", "img": "/dishes/chicken_lollipop.jpg"},
    {"cat": 6, "name": "Chicken Drumstick (3 Pcs)", "name_te": "చికెన్ డ్రమ్‌స్టిక్", "price": 260, "veg": False, "desc": "Deep fried spiced chicken legs seasoned with aromatic herbs", "img": "/dishes/chicken_drumstick.jpg"},
    {"cat": 6, "name": "Dragon Chicken", "name_te": "డ్రాగన్ చికెన్", "price": 270, "veg": False, "desc": "Crispy chicken strips coated in fiery red chilli sauce with cashew nuts", "img": "/dishes/dragon_chicken.jpg"},
    {"cat": 6, "name": "Kung Pao Chicken", "name_te": "కుంగ్ పావో చికెన్", "price": 300, "veg": False, "desc": "Stir-fried chicken with peanuts, vegetables and spicy chili peppers", "img": "/dishes/kung_pao_chicken.jpg"},
    {"cat": 6, "name": "Arabeiq Special Chicken Starter", "name_te": "అరబిక్ స్పెషల్ చికెన్", "price": 300, "veg": False, "desc": "Chef special Arabian spiced boneless chicken roast with garlic dip", "img": "/dishes/arabieq_special_chicken_starter.jpg"},
    {"cat": 6, "name": "Khandani Chicken", "name_te": "ఖందానీ చికెన్", "price": 349, "veg": False, "desc": "Royal recipe boneless chicken tossed with saffron and rich dry fruits", "img": "/dishes/khandani_chicken.jpg"},
    {"cat": 6, "name": "Dubai Chicken Starter", "name_te": "దుబాయ్ చికెన్", "price": 300, "veg": False, "desc": "Middle Eastern style glazed chicken with sumac and toasted sesame", "img": "/dishes/dubai_chicken_starter.jpg"},
    {"cat": 6, "name": "Mutton 65", "name_te": "మటన్ 65", "price": 350, "veg": False, "desc": "Tender boneless mutton chunks tossed in spicy South Indian 65 masala", "img": "/dishes/mutton_65.jpg"},
    {"cat": 6, "name": "Mutton Chilly Dry", "name_te": "మటన్ చిల్లీ", "price": 350, "veg": False, "desc": "Spiced tender mutton tossed with onions and spicy green chillies", "img": "/dishes/mutton_sukka.jpg"},
    {"cat": 6, "name": "Fish Finger (8 Pcs)", "name_te": "ఫిష్ ఫింగర్స్", "price": 350, "veg": False, "desc": "Crumb-fried crispy fish fillets served with tartar sauce", "img": "/dishes/fish_finger.jpg"},
    {"cat": 6, "name": "Apollo Fish", "name_te": "అపోలో ఫిష్", "price": 350, "veg": False, "desc": "Hyderabadi style boneless fish fillets tossed in spicy curd tadka", "img": "/dishes/apollo_fish.jpg"},
    {"cat": 6, "name": "Fish 65", "name_te": "ఫిష్ 65", "price": 350, "veg": False, "desc": "Spicy crispy fried fish morsels with curry leaves and green chillies", "img": "/dishes/apollo_fish.jpg"},
    {"cat": 6, "name": "Balu Prawns", "name_te": "బాలు ప్రాన్స్", "price": 350, "veg": False, "desc": "Crispy fried prawns tossed in spicy house special red masala", "img": "/dishes/apollo_fish.jpg"},
    {"cat": 6, "name": "Loose Prawns", "name_te": "లూస్ ప్రాన్స్", "price": 350, "veg": False, "desc": "Crispy batter-fried juicy prawns seasoned with salt & pepper", "img": "/dishes/apollo_fish.jpg"},
    {"cat": 6, "name": "Chilly Prawns", "name_te": "చిల్లీ ప్రాన్స్", "price": 350, "veg": False, "desc": "Juicy prawns tossed in spicy Chinese chilly garlic sauce", "img": "/dishes/apollo_fish.jpg"},
    {"cat": 6, "name": "Egg 65", "name_te": "ఎగ్ 65", "price": 170, "veg": False, "desc": "Batter-fried boiled egg cubes tossed in tangy 65 masala", "img": "/dishes/chicken_65.jpg"},
    {"cat": 6, "name": "Teetar Fry (Quail Fry)", "name_te": "తీతర్ ఫ్రై", "price": 250, "veg": False, "desc": "Traditional spiced dry-fried quail with regional South Indian masala", "img": "/dishes/mutton_chops.jpg"},
    {"cat": 6, "name": "Natu Kodi Fry (Country Chicken)", "name_te": "నాటుకోడి ఫ్రై", "price": 350, "veg": False, "desc": "Country chicken dry roast with crushed black pepper and green chillies", "img": "/dishes/arabieq_special_chicken_starter.jpg"},
    {"cat": 6, "name": "Gongura Natu Kodi", "name_te": "గోంగూర నాటుకోడి", "price": 350, "veg": False, "desc": "Country chicken cooked with tangy Andhra sorrel leaves and spices", "img": "/dishes/khandani_chicken.jpg"},

    # 7. Indian Bread Items (Page 7)
    {"cat": 7, "name": "Tandoori Roti", "name_te": "రొటీ", "price": 20, "veg": True, "desc": "Clay oven baked whole wheat flatbread", "img": "/dishes/3d_curries.jpg"},
    {"cat": 7, "name": "Butter Roti", "name_te": "బట్టర్ రొటీ", "price": 25, "veg": True, "desc": "Tandoori whole wheat roti brushed with melting butter", "img": "/dishes/3d_curries.jpg"},
    {"cat": 7, "name": "Plain Naan", "name_te": "నాన్", "price": 25, "veg": True, "desc": "Soft and fluffy refined flour bread baked in tandoor", "img": "/dishes/3d_curries.jpg"},
    {"cat": 7, "name": "Butter Naan", "name_te": "బట్టర్ నాన్", "price": 30, "veg": True, "desc": "Classic tandoori naan brushed with rich dairy butter", "img": "/dishes/3d_curries.jpg"},
    {"cat": 7, "name": "Garlic Naan", "name_te": "గార్లిక్ నాన్", "price": 35, "veg": True, "desc": "Tandoori naan topped with roasted minced garlic and coriander", "img": "/dishes/3d_curries.jpg"},
    {"cat": 7, "name": "Chilli Garlic Naan", "name_te": "చిల్లీ గార్లిక్ నాన్", "price": 40, "veg": True, "desc": "Naan topped with spicy green chillies and roasted garlic", "img": "/dishes/3d_curries.jpg"},
    {"cat": 7, "name": "Masala Kulcha", "name_te": "మసాలా కుల్చా", "price": 40, "veg": True, "desc": "Soft leavened bread stuffed with spiced potato and onion filling", "img": "/dishes/3d_curries.jpg"},
    {"cat": 7, "name": "Paneer Kulcha", "name_te": "పన్నీర్ కుల్చా", "price": 50, "veg": True, "desc": "Tandoori kulcha stuffed with seasoned fresh grated paneer", "img": "/dishes/3d_curries.jpg"},
    {"cat": 7, "name": "Rumali Roti", "name_te": "రుమాలి రొటీ", "price": 40, "veg": True, "desc": "Ultra-thin and soft handkerchief style flatbread", "img": "/dishes/3d_curries.jpg"},
    {"cat": 7, "name": "Kashmiri Naan", "name_te": "కాశ్మీరీ నాన్", "price": 150, "veg": True, "desc": "Sweet tandoori naan stuffed with dry fruits, cherries and nuts", "img": "/dishes/3d_curries.jpg"},
    {"cat": 7, "name": "Cheese Garlic Naan", "name_te": "చీజ్ గార్లిక్ నాన్", "price": 60, "veg": True, "desc": "Naan loaded with melted cheese and aromatic roasted garlic", "img": "/dishes/3d_curries.jpg"},
    {"cat": 7, "name": "Roti Basket (Assorted 5 Breads)", "name_te": "రొటీ బాస్కెట్", "price": 150, "veg": True, "desc": "Assortment of Roti, Butter Naan, Garlic Naan, Kulcha and Paratha", "img": "/dishes/3d_curries.jpg"},

    # 8. Biryani & Pulavs (Page 7 & 8)
    {"cat": 8, "name": "Chicken Dum Biryani (Regular)", "name_te": "చికెన్ దమ్ బిర్యానీ", "price": 220, "veg": False, "desc": "Authentic Hyderabadi basmati biryani slow cooked on dum with marinated chicken", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Chicken Dum Biryani (Large)", "name_te": "చికెన్ దమ్ బిర్యానీ (లార్జ్)", "price": 350, "veg": False, "desc": "Large portion of Hyderabadi chicken dum biryani with extra gravy and raita", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Chicken Dum Biryani (Jumbo Family Pack)", "name_te": "చికెన్ దమ్ బిర్యానీ (జంబో)", "price": 600, "veg": False, "desc": "Jumbo feast biryani for 3-4 persons with chicken starters and dessert", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Tandoori Chicken Biryani", "name_te": "తందూరి చికెన్ బిర్యానీ", "price": 260, "veg": False, "desc": "Biryani rice topped with juicy charred tandoori roasted chicken", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Mughalai Chicken Biryani", "name_te": "మొఘలాయి చికెన్ బిర్యానీ", "price": 260, "veg": False, "desc": "Rich biryani with egg drop gravy and boneless succulent chicken pieces", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Tangdi Chicken Biryani", "name_te": "టాంగ్డీ చికెన్ బిర్యానీ", "price": 280, "veg": False, "desc": "Flavored biryani served with marinated roasted chicken drumsticks", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Chicken Tikka Biryani", "name_te": "చికెన్ టిక్కా బిర్యానీ", "price": 280, "veg": False, "desc": "Aromatic biryani layered with smoky boneless chicken tikka kebabs", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Gongura Chicken Biryani", "name_te": "గోంగూర చికెన్ బిర్యానీ", "price": 280, "veg": False, "desc": "Andhra specialty biryani spiced with tangy gongura sorrel leaves", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Ulava Charu Chicken Biryani", "name_te": "ఉలవచారు చికెన్ బిర్యానీ", "price": 280, "veg": False, "desc": "Basmati rice enriched with traditional horsegram soup reduction and chicken", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Fry Chicken Biryani (Special)", "name_te": "ఫ్రై చికెన్ బిర్యానీ", "price": 240, "veg": False, "desc": "Biryani rice topped with spicy fried bone-in chicken pieces", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Arabeiq Special Chicken Biryani", "name_te": "అరబిక్ స్పెషల్ చికెన్ బిర్యానీ", "price": 300, "veg": False, "desc": "House specialty biryani with boneless meat, saffron essence and cashew dry fruits", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Mutton Chitti Muthyal Biryani", "name_te": "మటన్ చిట్టి ముత్యాల బిర్యానీ", "price": 350, "veg": False, "desc": "Traditional small grain aromatic rice biryani with succulent tender mutton", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Gongura Mutton Biryani", "name_te": "గోంగూర మటన్ బిర్యానీ", "price": 350, "veg": False, "desc": "Spicy mutton biryani infused with sour gongura paste and green chillies", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Kachi Ghosh Mutton Biryani", "name_te": "కచ్చి ఘోష్ మటన్ బిర్యానీ", "price": 350, "veg": False, "desc": "Raw marinated mutton slow-cooked with basmati rice in authentic royal dum style", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Veg Dum Biryani", "name_te": "వెజ్ దమ్ బిర్యానీ", "price": 180, "veg": True, "desc": "Layered basmati rice with mixed seasonal vegetables, paneer and saffron", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Paneer Biryani", "name_te": "పన్నీర్ బిర్యానీ", "price": 240, "veg": True, "desc": "Fragrant biryani rice cooked with marinated fresh paneer cubes and herbs", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Mushroom Biryani", "name_te": "మష్రూమ్ బిర్యానీ", "price": 220, "veg": True, "desc": "Spiced button mushrooms layered with aromatic long-grain basmati rice", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Kaju Paneer Biryani", "name_te": "కాజు పన్నీర్ బిర్యానీ", "price": 260, "veg": True, "desc": "Royal vegetarian biryani loaded with roasted cashew nuts and cottage cheese", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Raju Gari Kodi Pulav", "name_te": "రాజుగారి కోడి పులావ్", "price": 300, "veg": False, "desc": "Authentic Godavari style spiced chicken pulav cooked in ghee and green chillies", "img": "/dishes/3d_biryani.jpg"},
    {"cat": 8, "name": "Kaju Pulav", "name_te": "కాజు పులావ్", "price": 280, "veg": True, "desc": "Ghee roasted basmati rice cooked with whole cashew nuts and whole spices", "img": "/dishes/3d_biryani.jpg"},

    # 9. Curries & Main Course (Page 8 & 9)
    {"cat": 9, "name": "Dal Tadka", "name_te": "దాల్ తడ్కా", "price": 170, "veg": True, "desc": "Yellow lentils tempered with ghee, cumin seeds, garlic and red chillies", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Dal Makhani", "name_te": "దాల్ మఖ్నీ", "price": 190, "veg": True, "desc": "Slow cooked black lentils simmered with fresh butter and dairy cream", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Paneer Butter Masala", "name_te": "పన్నీర్ బట్టర్ మసాలా", "price": 270, "veg": True, "desc": "Soft paneer cubes in a rich, buttery tomato cream gravy", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Kadai Paneer", "name_te": "కడాయ్ పన్నీర్", "price": 260, "veg": True, "desc": "Paneer tossed with capsicum, onions and freshly ground coriander spices", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Shahi Paneer", "name_te": "షాహీ పన్నీర్", "price": 280, "veg": True, "desc": "Royal paneer curry in a creamy cashew nut and almond gravy", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Palak Paneer", "name_te": "పాలక్ పన్నీర్", "price": 260, "veg": True, "desc": "Fresh cottage cheese in a smooth spiced spinach purée", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Kaju Paneer Masala", "name_te": "కాజు పన్నీర్ మసాలా", "price": 300, "veg": True, "desc": "Paneer and roasted cashews simmered in a spiced onion tomato gravy", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Mushroom Masala", "name_te": "మష్రూమ్ మసాలా", "price": 220, "veg": True, "desc": "Fresh button mushrooms cooked in an aromatic spiced onion tomato curry", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Chicken Curry (Bone)", "name_te": "చికెన్ కర్రీ", "price": 260, "veg": False, "desc": "Homestyle South Indian chicken curry in a flavorful onion gravy", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Chicken Butter Masala (Boneless)", "name_te": "చికెన్ బట్టర్ మసాలా", "price": 280, "veg": False, "desc": "Succulent tandoori chicken pieces in a silky makhani gravy", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Kadai Chicken Curry", "name_te": "కడాయ్ చికెన్", "price": 260, "veg": False, "desc": "Chicken pieces cooked with bell peppers and roasted kadai masala", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Chicken Tikka Masala", "name_te": "చికెన్ టిక్కా మసాలా", "price": 300, "veg": False, "desc": "Smoky char-grilled chicken tikka in a spiced tomato cream sauce", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Mughlai Chicken Curry", "name_te": "మొఘలాయి చికెన్", "price": 280, "veg": False, "desc": "Mild and rich chicken gravy made with eggs, nuts and cream", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Gongura Natukodi Pulusu", "name_te": "గోంగూర నాటుకోడి పులుసు", "price": 350, "veg": False, "desc": "Authentic country chicken stew simmered with sour sorrel leaves", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Mutton Rogan Josh", "name_te": "మటన్ రోగన్ జోష్", "price": 350, "veg": False, "desc": "Tender lamb pieces in a fragrant Kashmiri red chilli and cardamom gravy", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Dum Ka Mutton Curry", "name_te": "దమ్ కా మటన్", "price": 350, "veg": False, "desc": "Slow dum-cooked mutton in a thick caramelized onion and cashew paste", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Prawns Masala Curry", "name_te": "ప్రాన్స్ మసాలా", "price": 350, "veg": False, "desc": "Fresh prawns simmered in a spiced coastal coconut tomato gravy", "img": "/dishes/3d_curries.jpg"},
    {"cat": 9, "name": "Fish Masala Curry", "name_te": "ఫిష్ మసాలా", "price": 350, "veg": False, "desc": "Tender fish fillets cooked in a tangy tamarind and onion masala", "img": "/dishes/3d_curries.jpg"},

    # 10. Arabian Mandi, Al-Faham & Shawarma (Page 10 & 11)
    {"cat": 10, "name": "Chicken Mandi (Single)", "name_te": "చికెన్ మండి", "price": 250, "veg": False, "desc": "Fragrant mandi rice served with tender roasted Arabian spiced chicken and tomato salsa", "img": "/dishes/3d_mandi.jpg"},
    {"cat": 10, "name": "Chicken Grill Mandi", "name_te": "చికెన్ గ్రిల్ మండి", "price": 280, "veg": False, "desc": "Mandi rice served with char-grilled smoky quarter chicken", "img": "/dishes/3d_mandi.jpg"},
    {"cat": 10, "name": "Chicken Alfaham Mandi", "name_te": "చికెన్ అల్-ఫహమ్ మండి", "price": 280, "veg": False, "desc": "Arabian rice topped with flame-grilled Al-Faham marinated chicken", "img": "/dishes/3d_mandi.jpg"},
    {"cat": 10, "name": "Chicken Juicy Mandi", "name_te": "చికెన్ జ్యూసీ మండి", "price": 350, "veg": False, "desc": "Mandi rice paired with extra tender chicken tossed in rich juicy sauce", "img": "/dishes/3d_mandi.jpg"},
    {"cat": 10, "name": "Jumbo Chicken Mandi (Serves 5)", "name_te": "జంబో చికెన్ మండి (5 మందికి)", "price": 1200, "veg": False, "desc": "Grand party platter of Mandi rice with whole chicken, boiled eggs, fried nuts and sauces", "img": "/dishes/3d_mandi.jpg"},
    {"cat": 10, "name": "Mutton Mandi (Single)", "name_te": "మటన్ మండి", "price": 350, "veg": False, "desc": "Arabian basmati rice topped with melt-in-mouth slow cooked mutton", "img": "/dishes/3d_mandi.jpg"},
    {"cat": 10, "name": "Mutton Juicy Mandi", "name_te": "మటన్ జ్యూసీ మండి", "price": 450, "veg": False, "desc": "Aromatic mandi rice with succulent mutton in rich glaze", "img": "/dishes/3d_mandi.jpg"},
    {"cat": 10, "name": "Mutton Sheekh Kabab Mandi", "name_te": "మటన్ షీక్ కబాబ్ మండి", "price": 450, "veg": False, "desc": "Spiced minced lamb skewers served over fragrant mandi rice", "img": "/dishes/3d_mandi.jpg"},
    {"cat": 10, "name": "Jumbo Mutton Mandi (Serves 5)", "name_te": "జంబో మటన్ మండి (5 మందికి)", "price": 1700, "veg": False, "desc": "Grand royal platter with large mutton cuts, dry fruits, eggs and salads", "img": "/dishes/3d_mandi.jpg"},
    {"cat": 10, "name": "Prawns 65 Mandi", "name_te": "ప్రాన్స్ 65 మండి", "price": 400, "veg": False, "desc": "Mandi rice topped with spicy batter-fried crispy prawns", "img": "/dishes/3d_mandi.jpg"},
    {"cat": 10, "name": "Fish Tikka Mandi", "name_te": "ఫిష్ టిక్కా మండి", "price": 400, "veg": False, "desc": "Tandoori grilled fish fillets served over aromatic Arabian rice", "img": "/dishes/3d_mandi.jpg"},
    {"cat": 10, "name": "Platter Mandi Mix (Special)", "name_te": "ప్లాటర్ మండి మిక్స్", "price": 2000, "veg": False, "desc": "Ultimate feast: Chicken, Mutton, Fish & Prawns served over royal Mandi rice", "img": "/dishes/3d_mandi.jpg"},
    {"cat": 10, "name": "Classic Chicken Shawarma", "name_te": "చికెన్ షవర్మా", "price": 100, "veg": False, "desc": "Shredded rotisserie chicken with garlic toum sauce in fresh pita bread", "img": "/dishes/3d_shawarma.jpg"},
    {"cat": 10, "name": "Special Shawarma Full Chicken", "name_te": "స్పెషల్ షవర్మా ఫుల్ చికెన్", "price": 150, "veg": False, "desc": "Extra loaded chicken shawarma with no veggies, pure chicken & garlic dip", "img": "/dishes/3d_shawarma.jpg"},
    {"cat": 10, "name": "Plate Shawarma (2 Roti)", "name_te": "ప్లేట్ షవర్మా (2 రోటీ)", "price": 200, "veg": False, "desc": "Deconstructed shawarma platter with 2 rumali rotis, french fries and garlic dip", "img": "/dishes/3d_shawarma.jpg"},
    {"cat": 10, "name": "Burger Shawarma", "name_te": "బర్గర్ షవర్మా", "price": 90, "veg": False, "desc": "Toasted burger bun packed with shawarma chicken and mayo", "img": "/dishes/3d_shawarma.jpg"},
    {"cat": 10, "name": "Cheese Shawarma", "name_te": "చీజ్ షవర్మా", "price": 120, "veg": False, "desc": "Shawarma wrap loaded with melted cheese and seasoned chicken", "img": "/dishes/3d_shawarma.jpg"},
    {"cat": 10, "name": "Grilled Chicken (1 Full)", "name_te": "గ్రిల్డ్ చికెన్ (ఫుల్)", "price": 450, "veg": False, "desc": "Full whole chicken marinated in Arabian spices and charcoal grilled", "img": "/dishes/3d_shawarma.jpg"},
    {"cat": 10, "name": "Grilled Chicken (Half)", "name_te": "గ్రిల్డ్ చికెన్ (హాఫ్)", "price": 230, "veg": False, "desc": "Half chicken slow-grilled to smoky golden perfection", "img": "/dishes/3d_shawarma.jpg"},
    {"cat": 10, "name": "Special Al-Faham (1 Full)", "name_te": "స్పెషల్ అల్-ఫహమ్ (ఫుల్)", "price": 450, "veg": False, "desc": "Arabian charcoal barbecue chicken marinated in yogurt and Arabic spices", "img": "/dishes/3d_shawarma.jpg"},
    {"cat": 10, "name": "Special Al-Faham (Half)", "name_te": "స్పెషల్ అల్-ఫహమ్ (హాఫ్)", "price": 230, "veg": False, "desc": "Half Al-Faham chicken served with kuboos, garlic paste and pickled veggies", "img": "/dishes/3d_shawarma.jpg"},
    {"cat": 10, "name": "Peri Peri Al-Faham (Full)", "name_te": "పెరి పెరి అల్-ఫహమ్ (ఫుల్)", "price": 460, "veg": False, "desc": "Spicy African bird's eye chilli glaze over juicy flame-grilled chicken", "img": "/dishes/3d_shawarma.jpg"},
    {"cat": 10, "name": "Peri Peri Honey Al-Faham (Full)", "name_te": "పెరి పెరి హనీ అల్-ఫహమ్", "price": 480, "veg": False, "desc": "Fiery peri-peri spice balanced with sweet honey glaze on grilled chicken", "img": "/dishes/3d_shawarma.jpg"},
    {"cat": 10, "name": "Broasted Crispy Chicken (Single Pc)", "name_te": "బ్రోస్టెడ్ క్రిస్పీ చికెన్", "price": 89, "veg": False, "desc": "Pressure-fried crispy crunchy chicken with secret herb crust", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 10, "name": "Broasted Chicken 12 Pcs Pack", "name_te": "బ్రోస్టెడ్ 12 పీస్ ప్యాక్", "price": 549, "veg": False, "desc": "Family bucket: 3 Leg Pcs, 3 Lollipops, 3 Strips, 3 Hot Wings & French Fries", "img": "/dishes/3d_beverages.jpg"},

    # 11. Beverages, Shakes & Desserts (Page 12 & 13)
    {"cat": 11, "name": "Dry Fruit Special Shake", "name_te": "డ్రై ఫ్రూట్ స్పెషల్ షేక్", "price": 119, "veg": True, "desc": "Rich milk shake packed with almonds, pistachios, cashews, figs and dates", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 11, "name": "Kaju Milkshake", "name_te": "కాజు షేక్", "price": 149, "veg": True, "desc": "Creamy milkshake blended with premium roasted cashews", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 11, "name": "Badam Milkshake", "name_te": "బాదం షేక్", "price": 149, "veg": True, "desc": "Traditional chilled badam milk flavored with real saffron and crushed almonds", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 11, "name": "Anjeer Shake (Fig)", "name_te": "అంజీర్ షేక్", "price": 149, "veg": True, "desc": "Thick healthy shake made from premium dried figs and cold milk", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 11, "name": "KitKat Shake", "name_te": "కిట్‌క్యాట్ షేక్", "price": 99, "veg": True, "desc": "Crunchy KitKat wafer blended with creamy chocolate ice cream", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 11, "name": "Oreo Shake", "name_te": "ఓరియో షేక్", "price": 89, "veg": True, "desc": "Classic cookies and cream milkshake with chocolate drizzle", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 11, "name": "Ferrero Rocher Shake", "name_te": "ఫెర్రెరో రోచర్ షేక్", "price": 99, "veg": True, "desc": "Premium hazelnut chocolate shake topped with chocolate shavings", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 11, "name": "Arabian Fantasy Shake", "name_te": "అరేబియన్ ఫాంటసీ షేక్", "price": 119, "veg": True, "desc": "Exotic shake with dates, honey, nuts and vanilla ice cream", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 11, "name": "Strawberry Mojito", "name_te": "స్ట్రాబెర్రీ మొజితో", "price": 89, "veg": True, "desc": "Refreshing cooler with muddled strawberries, mint and lime soda", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 11, "name": "Virgin Mojito", "name_te": "వర్జిన్ మొజితో", "price": 79, "veg": True, "desc": "Crisp mint leaves, lime wedges, sugar syrup and sparkling soda", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 11, "name": "Blue Lagoon Mocktail", "name_te": "బ్లూ లగూన్", "price": 89, "veg": True, "desc": "Electric blue curacao syrup mixed with citrus lime and sprite", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 11, "name": "Royal Falooda", "name_te": "రాయల్ ఫలూదా", "price": 189, "veg": True, "desc": "Rose syrup, sabja seeds, vermicelli, rich milk topped with ice cream scoops and dry fruits", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 11, "name": "Dry Fruit Falooda (Arabeiq Special)", "name_te": "డ్రై ఫ్రూట్ ఫలూదా", "price": 199, "veg": True, "desc": "Loaded with roasted almonds, cashews, figs, kulfi ice cream and rose milk", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 11, "name": "Cold Coffee Classic", "name_te": "కోల్డ్ కాఫీ", "price": 49, "veg": True, "desc": "Rich espresso blended with chilled milk and ice cream", "img": "/dishes/3d_beverages.jpg"},
    {"cat": 11, "name": "Sweet Lassi", "name_te": "స్వీట్ లస్సీ", "price": 49, "veg": True, "desc": "Thick traditional churned sweet yogurt topped with malai", "img": "/dishes/3d_desserts.jpg"},
    {"cat": 11, "name": "Mango Lassi", "name_te": "మ్యాంగో లస్సీ", "price": 79, "veg": True, "desc": "Sweet lassi blended with rich Alphonso mango pulp", "img": "/dishes/3d_desserts.jpg"},
    {"cat": 11, "name": "Fresh Lime Soda (Sweet / Salt)", "name_te": "లెమన్ సోడా", "price": 29, "veg": True, "desc": "Freshly squeezed lemon juice with chilled sparkling soda", "img": "/dishes/3d_desserts.jpg"},
    {"cat": 11, "name": "Fresh Watermelon Juice", "name_te": "వాటర్‌మెలన్ జ్యూస్", "price": 49, "veg": True, "desc": "100% pure fresh watermelon juice served chilled", "img": "/dishes/3d_desserts.jpg"},
    {"cat": 11, "name": "Fresh Pomegranate Juice", "name_te": "దానిమ్మ జ్యూస్", "price": 79, "veg": True, "desc": "Freshly cold-pressed sweet pomegranate pearls juice", "img": "/dishes/3d_desserts.jpg"},
    {"cat": 11, "name": "Ice Cream Scoop (Single / Double)", "name_te": "ఐస్ క్రీమ్ స్కూప్", "price": 40, "veg": True, "desc": "Choice of Vanilla, Chocolate, Strawberry, Mango, Butterscotch or Pista", "img": "/dishes/3d_desserts.jpg"},
]
