"""
Surya Family Restaurant Kadiri — Authentic Menu Dataset
Dhandubatu Street, Bypass Road, Opp. RTC Bus Stand, Kadiri, Andhra Pradesh
Phone: +91 98803 58634 | Google Rating: 4.8 ★
"""

CATEGORIES = [
    {
        "id": 1,
        "name": "Biryani & Pulao Specials",
        "name_te": "బిర్యానీ & పులావ్ స్పెషల్స్",
        "icon": "Flame",
        "sort_order": 1,
        "is_active": True,
        "image_url": "/dishes/3d_biryani.jpg",
    },
    {
        "id": 2,
        "name": "Punjabi & North Indian Curries",
        "name_te": "పంజాబీ & నార్త్ ఇండియన్ కూరలు",
        "icon": "UtensilsCrossed",
        "sort_order": 2,
        "is_active": True,
        "image_url": "/dishes/3d_curries.jpg",
    },
    {
        "id": 3,
        "name": "Tandoori & Kebabs",
        "name_te": "తందూరి & కబాబ్స్",
        "icon": "Flame",
        "sort_order": 3,
        "is_active": True,
        "image_url": "/dishes/3d_nonveg_starters.jpg",
    },
    {
        "id": 4,
        "name": "Non-Veg Starters & Andhra Specials",
        "name_te": "నాన్-వెజ్ స్టార్టర్స్ & ఆంధ్రా స్పెషల్స్",
        "icon": "Flame",
        "sort_order": 4,
        "is_active": True,
        "image_url": "/dishes/chicken_lollipop.jpg",
    },
    {
        "id": 5,
        "name": "Veg Starters & Crispies",
        "name_te": "వెజ్ స్టార్టర్స్ & క్రిస్పీస్",
        "icon": "Salad",
        "sort_order": 5,
        "is_active": True,
        "image_url": "/dishes/3d_veg_starters.jpg",
    },
    {
        "id": 6,
        "name": "Indian Breads & Naans",
        "name_te": "రొట్టెలు, నాన్స్ & కుల్చా",
        "icon": "CircleDot",
        "sort_order": 6,
        "is_active": True,
        "image_url": "/dishes/3d_curries.jpg",
    },
    {
        "id": 7,
        "name": "Chinese, Fried Rice & Noodles",
        "name_te": "చైనీస్, ఫ్రైడ్ రైస్ & నూడుల్స్",
        "icon": "Utensils",
        "sort_order": 7,
        "is_active": True,
        "image_url": "/dishes/3d_biryani.jpg",
    },
    {
        "id": 8,
        "name": "Soups & Shorba",
        "name_te": "సూప్స్ & షోర్బా",
        "icon": "Soup",
        "sort_order": 8,
        "is_active": True,
        "image_url": "/dishes/mutton_maraq_soup.jpg",
    },
    {
        "id": 9,
        "name": "Rice & South Indian Meals",
        "name_te": "రైస్ & సౌత్ ఇండియన్ స్పెషల్స్",
        "icon": "Utensils",
        "sort_order": 9,
        "is_active": True,
        "image_url": "/dishes/curd.jpg",
    },
    {
        "id": 10,
        "name": "Coolers, Beverages & Desserts",
        "name_te": "కూలర్స్, పానీయాలు & స్వీట్స్",
        "icon": "Wine",
        "sort_order": 10,
        "is_active": True,
        "image_url": "/dishes/kunafa.jpg",
    },
]

ITEMS = [
    # 1. Biryani & Pulao Specials
    {
        "cat": 1,
        "name": "Surya Special Hyderabadi Chicken Dum Biryani",
        "name_te": "సూర్య స్పెషల్ చికెన్ దమ్ బిర్యానీ",
        "price": 260,
        "veg": False,
        "desc": "Long-grain fragrant basmati rice slow-cooked with tender spiced chicken, saffron, and aromatic spices. Served with mirchi ka salan & raita.",
        "img": "/dishes/3d_biryani.jpg",
        "is_best_seller": True,
        "variants": [
            {"name": "Single (Regular)", "name_te": "సింగిల్", "price": 190, "is_default": False},
            {"name": "Full (Serves 2)", "name_te": "ఫుల్ (ఇద్దరికి)", "price": 260, "is_default": True},
            {"name": "Family Pack (Serves 4)", "name_te": "ఫ్యామిలీ ప్యాక్ (నలుగురికి)", "price": 540, "is_default": False},
            {"name": "Jumbo Pack (Serves 6)", "name_te": "జంబో ప్యాక్ (ఆరుగురికి)", "price": 790, "is_default": False},
        ],
        "addons": [
            {"name": "Extra Biryani Rice", "name_te": "ఎక్స్ట్రా బిర్యానీ రైస్", "price": 110},
            {"name": "Extra Boiled Egg (1 pc)", "name_te": "ఎక్స్ట్రా గుడ్డు", "price": 20},
            {"name": "Extra Salan & Raita", "name_te": "సాలన్ & రైతా", "price": 30},
        ],
    },
    {
        "cat": 1,
        "name": "Chicken Fry Piece Biryani (Andhra Special)",
        "name_te": "చికెన్ ఫ్రై పీస్ బిర్యానీ",
        "price": 280,
        "veg": False,
        "desc": "Aromatic biryani rice layered with crispy Andhra-style roasted chicken fry pieces and caramelized onions.",
        "img": "/dishes/3d_biryani.jpg",
        "is_best_seller": True,
        "variants": [
            {"name": "Single", "name_te": "సింగిల్", "price": 200, "is_default": False},
            {"name": "Full", "name_te": "ఫుల్", "price": 280, "is_default": True},
            {"name": "Family Pack", "name_te": "ఫ్యామిలీ ప్యాక్", "price": 580, "is_default": False},
        ],
    },
    {
        "cat": 1,
        "name": "Special Mutton Dum Biryani",
        "name_te": "మటన్ దమ్ బిర్యానీ",
        "price": 360,
        "veg": False,
        "desc": "Juicy tender pieces of baby lamb marinated in authentic spices and dum-cooked with aged basmati rice.",
        "img": "/dishes/3d_biryani.jpg",
        "is_best_seller": True,
        "variants": [
            {"name": "Full", "name_te": "ఫుల్", "price": 360, "is_default": True},
            {"name": "Family Pack", "name_te": "ఫ్యామిలీ ప్యాక్", "price": 750, "is_default": False},
        ],
    },
    {
        "cat": 1,
        "name": "Kaju Paneer Biryani",
        "name_te": "కాజు పన్నీర్ బిర్యానీ",
        "price": 250,
        "veg": True,
        "desc": "Fragrant dum biryani rice tossed with roasted whole cashews (kaju) and soft malai paneer cubes.",
        "img": "/dishes/3d_biryani.jpg",
        "variants": [
            {"name": "Regular", "name_te": "రెగ్యులర్", "price": 250, "is_default": True},
            {"name": "Family Pack", "name_te": "ఫ్యామిలీ ప్యాక్", "price": 520, "is_default": False},
        ],
    },
    {
        "cat": 1,
        "name": "Surya Special Veg Dum Biryani",
        "name_te": "వెజ్ దమ్ బిర్యానీ",
        "price": 210,
        "veg": True,
        "desc": "Farm-fresh vegetables, green peas, and paneer cooked on dum with aromatic whole spices and saffron rice.",
        "img": "/dishes/3d_biryani.jpg",
    },
    {
        "cat": 1,
        "name": "Egg Dum Biryani",
        "name_te": "ఎగ్ దమ్ బిర్యానీ",
        "price": 220,
        "veg": False,
        "desc": "Golden shallow-fried boiled eggs spiced with masala, layered over aromatic Hyderabadi biryani rice.",
        "img": "/dishes/3d_biryani.jpg",
    },

    # 2. Punjabi & North Indian Curries (Celebrated in Reviews!)
    {
        "cat": 2,
        "name": "Punjabi Chicken Curry (Chef Special)",
        "name_te": "పంజాబీ చికెన్ కర్రీ",
        "price": 260,
        "veg": False,
        "desc": "Traditional North Indian Dhaba-style chicken simmered with freshly ground coriander, tomatoes, ginger, and desi ghee. Pairs perfectly with Butter Naan!",
        "img": "/dishes/3d_curries.jpg",
        "is_best_seller": True,
    },
    {
        "cat": 2,
        "name": "Butter Chicken (Murgh Makhani)",
        "name_te": "బట్టర్ చికెన్",
        "price": 270,
        "veg": False,
        "desc": "Smoky char-grilled tandoori chicken cooked in a velvety tomato, cashew cream, and rich butter gravy.",
        "img": "/dishes/3d_curries.jpg",
        "is_best_seller": True,
    },
    {
        "cat": 2,
        "name": "Kadai Chicken",
        "name_te": "కడాయి చికెన్",
        "price": 250,
        "veg": False,
        "desc": "Tender chicken cooked with crunchy bell peppers, onions, and freshly roasted kadai spices.",
        "img": "/dishes/3d_curries.jpg",
    },
    {
        "cat": 2,
        "name": "Andhra Chicken Curry (Guntur Spiced)",
        "name_te": "ఆంధ్రా చికెన్ కర్రీ",
        "price": 240,
        "veg": False,
        "desc": "Fiery Rayalaseema/Andhra style chicken curry with local red chillies, poppy seeds, and roasted coconut gravy.",
        "img": "/dishes/3d_curries.jpg",
    },
    {
        "cat": 2,
        "name": "Paneer Butter Masala",
        "name_te": "పన్నీర్ బట్టర్ మసాలా",
        "price": 230,
        "veg": True,
        "desc": "Rich and creamy cottage cheese cubes bathed in smooth butter and cashew tomato gravy with kasuri methi.",
        "img": "/dishes/3d_curries.jpg",
        "is_best_seller": True,
    },
    {
        "cat": 2,
        "name": "Kadai Paneer",
        "name_te": "కడాయి పన్నీర్",
        "price": 230,
        "veg": True,
        "desc": "Cottage cheese cubes tossed with capsicum, diced onions, and freshly crushed spices in a rich gravy.",
        "img": "/dishes/3d_curries.jpg",
    },
    {
        "cat": 2,
        "name": "Kaju Tomato Curry",
        "name_te": "కాజు టొమాటో కర్రీ",
        "price": 250,
        "veg": True,
        "desc": "Crispy whole cashews cooked in a flavorful rich sweet-and-tangy tomato gravy.",
        "img": "/dishes/3d_curries.jpg",
    },
    {
        "cat": 2,
        "name": "Dal Tadka (Desi Ghee)",
        "name_te": "దాల్ తడ్కా",
        "price": 160,
        "veg": True,
        "desc": "Yellow toor dal tempered with cumin, garlic, red chillies, and aromatic pure desi ghee.",
        "img": "/dishes/3d_curries.jpg",
    },
    {
        "cat": 2,
        "name": "Mushroom Masala",
        "name_te": "మష్రూమ్ మసాలా",
        "price": 220,
        "veg": True,
        "desc": "Button mushrooms cooked in an onion-tomato spicy masala with whole aromatic herbs.",
        "img": "/dishes/3d_curries.jpg",
    },

    # 3. Tandoori & Kebabs
    {
        "cat": 3,
        "name": "Tandoori Chicken (Full / Half)",
        "name_te": "తందూరి చికెన్",
        "price": 260,
        "veg": False,
        "desc": "Whole chicken marinated overnight in Kashmiri chilli, spiced hung curd, and roasted over clay charcoal tandoor.",
        "img": "/dishes/3d_nonveg_starters.jpg",
        "is_best_seller": True,
        "variants": [
            {"name": "Half (2 Pcs)", "name_te": "హాఫ్ (2 ముక్కలు)", "price": 260, "is_default": True},
            {"name": "Full (4 Pcs)", "name_te": "ఫుల్ (4 ముక్కలు)", "price": 480, "is_default": False},
        ],
    },
    {
        "cat": 3,
        "name": "Chicken Tikka (6 Pcs)",
        "name_te": "చికెన్ టిక్కా (6)",
        "price": 250,
        "veg": False,
        "desc": "Boneless chicken chunks marinated in mustard oil, ajwain, and tandoori spices, char-grilled to perfection.",
        "img": "/dishes/3d_nonveg_starters.jpg",
    },
    {
        "cat": 3,
        "name": "Tangdi Kebab (3 Pcs)",
        "name_te": "టాంగ్డి కబాబ్ (3)",
        "price": 260,
        "veg": False,
        "desc": "Chicken drumsticks stuffed with cheese and spices, roasted golden in charcoal tandoor.",
        "img": "/dishes/3d_nonveg_starters.jpg",
    },
    {
        "cat": 3,
        "name": "Paneer Tikka (6 Pcs)",
        "name_te": "పన్నీర్ టిక్కా (6)",
        "price": 220,
        "veg": True,
        "desc": "Juicy chunks of malai paneer and crunchy peppers marinated in tandoori masala and grilled on skewers.",
        "img": "/dishes/3d_veg_starters.jpg",
    },

    # 4. Non-Veg Starters & Andhra Specials
    {
        "cat": 4,
        "name": "Chicken Lollipop (Saucy / Dry)",
        "name_te": "చికెన్ లాలిపాప్ (6)",
        "price": 240,
        "veg": False,
        "desc": "Crispy seasoned chicken winglets served crispy dry or tossed in spicy Indo-Chinese garlic sauce.",
        "img": "/dishes/chicken_lollipop.jpg",
        "is_best_seller": True,
    },
    {
        "cat": 4,
        "name": "Chilli Chicken",
        "name_te": "చిల్లీ చికెన్",
        "price": 240,
        "veg": False,
        "desc": "Crispy boneless chicken tossed with green chillies, onions, garlic, and dark soy sauce.",
        "img": "/dishes/3d_nonveg_starters.jpg",
    },
    {
        "cat": 4,
        "name": "Dragon Chicken",
        "name_te": "డ్రాగన్ చికెన్",
        "price": 250,
        "veg": False,
        "desc": "Crispy chicken strips tossed in spicy sweet chili sauce, roasted cashews, and sesame seeds.",
        "img": "/dishes/3d_nonveg_starters.jpg",
    },
    {
        "cat": 4,
        "name": "Apollo Fish",
        "name_te": "అపోలో ఫిష్",
        "price": 280,
        "veg": False,
        "desc": "Hyderabadi style boneless fish fillets spiced with curry leaves, yogurt, green chillies, and spices.",
        "img": "/dishes/3d_nonveg_starters.jpg",
    },
    {
        "cat": 4,
        "name": "Guntur Chicken Dry",
        "name_te": "గుంటూరు చికెన్ ఫ్రై",
        "price": 250,
        "veg": False,
        "desc": "Traditional spicy dry roasted chicken infused with Guntur red chillies and curry leaves.",
        "img": "/dishes/3d_nonveg_starters.jpg",
    },

    # 5. Veg Starters & Crispies
    {
        "cat": 5,
        "name": "Crispy Corn Pepper Salt",
        "name_te": "క్రిస్పీ కార్న్",
        "price": 180,
        "veg": True,
        "desc": "Golden fried American sweet corn tossed with freshly cracked black pepper, capsicum, and spring onions.",
        "img": "/dishes/3d_veg_starters.jpg",
        "is_best_seller": True,
    },
    {
        "cat": 5,
        "name": "Veg Manchurian (Dry)",
        "name_te": "వెజ్ మంచూరియా",
        "price": 170,
        "veg": True,
        "desc": "Crispy vegetable dumplings tossed with ginger, garlic, chopped onions, and Indo-Chinese sauces.",
        "img": "/dishes/3d_veg_starters.jpg",
    },
    {
        "cat": 5,
        "name": "Chilli Paneer (Dry)",
        "name_te": "చిల్లీ పన్నీర్",
        "price": 210,
        "veg": True,
        "desc": "Batter-fried paneer cubes wok-tossed with capsicum, garlic, spring onions, and green chillies.",
        "img": "/dishes/3d_veg_starters.jpg",
    },
    {
        "cat": 5,
        "name": "Gobi 65",
        "name_te": "గోబీ 65",
        "price": 160,
        "veg": True,
        "desc": "Crispy spiced cauliflower florets tossed with curry leaves, crushed pepper, and lemon juice.",
        "img": "/dishes/3d_veg_starters.jpg",
    },

    # 6. Indian Breads & Naans (Loved with Curries!)
    {
        "cat": 6,
        "name": "Butter Naan",
        "name_te": "బట్టర్ నాన్",
        "price": 50,
        "veg": True,
        "desc": "Soft, fluffy clay-oven leavened bread brushed generously with melting butter.",
        "img": "/dishes/3d_curries.jpg",
        "is_best_seller": True,
    },
    {
        "cat": 6,
        "name": "Garlic Butter Naan",
        "name_te": "గార్లిక్ బట్టర్ నాన్",
        "price": 65,
        "veg": True,
        "desc": "Tandoori naan topped with roasted garlic flakes, fresh coriander, and melted butter.",
        "img": "/dishes/3d_curries.jpg",
        "is_best_seller": True,
    },
    {
        "cat": 6,
        "name": "Tandoori Roti (Butter)",
        "name_te": "తందూరి రోటీ (బట్టర్)",
        "price": 30,
        "veg": True,
        "desc": "Whole wheat bread baked in clay tandoor and brushed with fresh butter.",
        "img": "/dishes/3d_curries.jpg",
    },
    {
        "cat": 6,
        "name": "Tandoori Roti (Plain)",
        "name_te": "తందూరి రోటీ (ప్లెయిన్)",
        "price": 25,
        "veg": True,
        "desc": "Crisp and healthy traditional whole wheat roti baked in charcoal tandoor.",
        "img": "/dishes/3d_curries.jpg",
    },
    {
        "cat": 6,
        "name": "Rumali Roti",
        "name_te": "రుమాలి రోటీ",
        "price": 35,
        "veg": True,
        "desc": "Hand-tossed ultra-thin, soft handkerchief-style Indian bread.",
        "img": "/dishes/3d_curries.jpg",
    },

    # 7. Chinese, Fried Rice & Noodles
    {
        "cat": 7,
        "name": "Surya Special Chicken Fried Rice",
        "name_te": "స్పెషల్ చికెన్ ఫ్రైడ్ రైస్",
        "price": 210,
        "veg": False,
        "desc": "Wok-tossed basmati rice with shredded chicken, scramble egg, crunchy veggies, and chef's special seasoning.",
        "img": "/dishes/3d_biryani.jpg",
    },
    {
        "cat": 7,
        "name": "Schezwan Chicken Fried Rice",
        "name_te": "షెజ్వాన్ చికెన్ ఫ్రైడ్ రైస్",
        "price": 220,
        "veg": False,
        "desc": "Spicy wok-fried rice tossed with fiery Schezwan sauce, chicken, and spring onions.",
        "img": "/dishes/3d_biryani.jpg",
    },
    {
        "cat": 7,
        "name": "Veg Fried Rice",
        "name_te": "వెజ్ ఫ్రైడ్ రైస్",
        "price": 170,
        "veg": True,
        "desc": "Classic wok-tossed rice with finely chopped carrots, beans, cabbage, and light soy sauce.",
        "img": "/dishes/3d_biryani.jpg",
    },
    {
        "cat": 7,
        "name": "Chicken Hakka Noodles",
        "name_te": "చికెన్ హక్కా నూడుల్స్",
        "price": 210,
        "veg": False,
        "desc": "Stir-fried noodles with shredded chicken, crisp cabbage, capsicum, and oriental spices.",
        "img": "/dishes/3d_biryani.jpg",
    },
    {
        "cat": 7,
        "name": "Veg Hakka Noodles",
        "name_te": "వెజ్ హక్కా నూడుల్స్",
        "price": 170,
        "veg": True,
        "desc": "Street-style stir-fried wheat noodles with garden fresh vegetables and mild spices.",
        "img": "/dishes/3d_biryani.jpg",
    },

    # 8. Soups & Shorba
    {
        "cat": 8,
        "name": "Chicken Manchow Soup",
        "name_te": "చికెన్ మంచోవ్ సూప్",
        "price": 130,
        "veg": False,
        "desc": "Hearty Indo-Chinese spiced soup with chicken and egg, topped with crispy fried noodles.",
        "img": "/dishes/mutton_maraq_soup.jpg",
    },
    {
        "cat": 8,
        "name": "Sweet Corn Chicken Soup",
        "name_te": "స్వీట్ కార్న్ చికెన్ సూప్",
        "price": 130,
        "veg": False,
        "desc": "Comforting creamy sweet corn soup with tender chicken shreds and egg drops.",
        "img": "/dishes/mutton_maraq_soup.jpg",
    },
    {
        "cat": 8,
        "name": "Cream of Tomato Soup",
        "name_te": "టొమాటో సూప్",
        "price": 110,
        "veg": True,
        "desc": "Silky smooth ripe tomato soup with butter, herbs, and crispy golden croutons.",
        "img": "/dishes/mutton_maraq_soup.jpg",
    },

    # 9. Rice & South Indian Specials
    {
        "cat": 9,
        "name": "Curd Rice (Bagala Bath)",
        "name_te": "పెరుగు అన్నం",
        "price": 100,
        "veg": True,
        "desc": "Cooling and creamy tempered homemade curd rice with mustard, ginger, green chillies, and pomegranate.",
        "img": "/dishes/curd.jpg",
        "is_best_seller": True,
    },
    {
        "cat": 9,
        "name": "Jeera Rice",
        "name_te": "జీరా రైస్",
        "price": 140,
        "veg": True,
        "desc": "Fragrant long-grain basmati rice tempered with roasted cumin seeds and fresh coriander in pure ghee.",
        "img": "/dishes/3d_biryani.jpg",
    },

    # 10. Coolers, Beverages & Desserts
    {
        "cat": 10,
        "name": "Fresh Lime Soda (Sweet / Salt)",
        "name_te": "లెమన్ సోడా",
        "price": 50,
        "veg": True,
        "desc": "Refreshing fizzy soda infused with freshly squeezed Kadiri lemon juice and mint.",
        "img": "/dishes/kunafa.jpg",
    },
    {
        "cat": 10,
        "name": "Sweet Lassi (Chilled)",
        "name_te": "స్వీట్ లస్సీ",
        "price": 60,
        "veg": True,
        "desc": "Thick whipped sweet yogurt lassi topped with malai and cardamom essence.",
        "img": "/dishes/kunafa.jpg",
    },
    {
        "cat": 10,
        "name": "Gulab Jamun with Vanilla Ice Cream (2 Pcs)",
        "name_te": "గులాబ్ జామూన్ విత్ ఐస్ క్రీం",
        "price": 90,
        "veg": True,
        "desc": "Warm, melt-in-the-mouth mawa gulab jamuns served alongside a scoop of rich vanilla ice cream.",
        "img": "/dishes/kunafa.jpg",
        "is_best_seller": True,
    },
    {
        "cat": 10,
        "name": "Apricot Delight (Surya Special)",
        "name_te": "ఆప్రికాట్ డిలైట్",
        "price": 120,
        "veg": True,
        "desc": "Rich layered dessert made of stewed Turkish apricots, sponge cake, and thick fresh cream.",
        "img": "/dishes/kunafa.jpg",
        "is_best_seller": True,
    },
    {
        "cat": 10,
        "name": "Thums Up / Soft Drinks (750ml)",
        "name_te": "కూల్ డ్రింక్",
        "price": 45,
        "veg": True,
        "desc": "Chilled beverage bottle.",
        "img": "/dishes/kunafa.jpg",
    },
]
