/**
 * Surya Family Restaurant Kadiri — Authentic Menu Dataset
 * Dhandubatu Street, Bypass Road, Opp. RTC Bus Stand, Kadiri, Andhra Pradesh
 * Phone: +91 98803 58634 | Google Rating: 4.8 ★ | UPI: SBIBHIM.INSTANT26821939387985481@sbipay
 * Synchronized with Official Database Schema and Seed Data
 */

export interface StaticVariant {
    id?: number;
    name: string;
    name_te?: string;
    price_paise: number;
    is_default: boolean;
    is_available?: boolean;
}

export interface StaticAddon {
    id?: number;
    name: string;
    name_te?: string;
    price_paise: number;
    is_available?: boolean;
}

export interface StaticMenuItem {
    id: number;
    category_id: number;
    name: string;
    name_te: string;
    description: string;
    price_paise: number;
    is_veg: boolean;
    is_spicy: boolean;
    is_best_seller: boolean;
    image_url: string;
    is_available: boolean;
    track_stock: boolean;
    stock_qty: number;
    low_stock_threshold: number;
    is_special: boolean;
    has_variants: boolean;
    variants?: StaticVariant[];
    addons?: StaticAddon[];
}

export interface StaticCategory {
    id: number;
    name: string;
    name_te: string;
    icon: string;
    sort_order?: number;
    image_url: string;
}

export const SURYA_CATEGORIES: StaticCategory[] = [
    {
        id: 1,
        name: "Biryani & Pulao Specials",
        name_te: "బిర్యానీ & పులావ్ స్పెషల్స్",
        icon: "Flame",
        sort_order: 1,
        image_url: "/dishes/cat_biryani.jpg",
    },
    {
        id: 2,
        name: "Punjabi & North Indian Curries",
        name_te: "పంజాబీ & నార్త్ ఇండియన్ కూరలు",
        icon: "UtensilsCrossed",
        sort_order: 2,
        image_url: "/dishes/cat_curries.jpg",
    },
    {
        id: 3,
        name: "Tandoori & Kebabs",
        name_te: "తందూరి & కబాబ్స్",
        icon: "Flame",
        sort_order: 3,
        image_url: "/dishes/cat_tandoori.jpg",
    },
    {
        id: 4,
        name: "Non-Veg Starters & Andhra Specials",
        name_te: "నాన్-వెజ్ స్టార్టర్స్ & ఆంధ్రా స్పెషల్స్",
        icon: "Flame",
        sort_order: 4,
        image_url: "/dishes/cat_nonveg_starters.jpg",
    },
    {
        id: 5,
        name: "Veg Starters & Crispies",
        name_te: "వెజ్ స్టార్టర్స్ & క్రిస్పీస్",
        icon: "Salad",
        sort_order: 5,
        image_url: "/dishes/cat_veg_starters.jpg",
    },
    {
        id: 6,
        name: "Indian Breads & Naans",
        name_te: "రొట్టెలు, నాన్స్ & కుల్చా",
        icon: "CircleDot",
        sort_order: 6,
        image_url: "/dishes/cat_breads.jpg",
    },
    {
        id: 7,
        name: "Chinese, Fried Rice & Noodles",
        name_te: "చైనీస్, ఫ్రైడ్ రైస్ & నూడుల్స్",
        icon: "Utensils",
        sort_order: 7,
        image_url: "/dishes/cat_chinese.jpg",
    },
    {
        id: 8,
        name: "Soups & Shorba",
        name_te: "సూప్స్ & షోర్బా",
        icon: "Soup",
        sort_order: 8,
        image_url: "/dishes/cat_soups.jpg",
    },
    {
        id: 9,
        name: "Rice & South Indian Meals",
        name_te: "రైస్ & సౌత్ ఇండియన్ స్పెషల్స్",
        icon: "Utensils",
        sort_order: 9,
        image_url: "/dishes/cat_south_rice.jpg",
    },
    {
        id: 10,
        name: "Coolers, Beverages & Desserts",
        name_te: "కూలర్స్, పానీయాలు & స్వీట్స్",
        icon: "Wine",
        sort_order: 10,
        image_url: "/dishes/cat_desserts.jpg",
    },
];

export const SURYA_MENU_ITEMS: StaticMenuItem[] = [
    {
        id: 1,
        category_id: 1,
        name: "Surya Special Hyderabadi Chicken Dum Biryani",
        name_te: "సూర్య స్పెషల్ చికెన్ దమ్ బిర్యానీ",
        description: "Long-grain fragrant basmati rice slow-cooked with tender spiced chicken, saffron, and aromatic spices. Served with mirchi ka salan & raita.",
        price_paise: 26000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/hyderabadi_chicken_dum_biryani.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: true,
        has_variants: true,
        variants: [
            {
                name: "Single (Regular)",
                name_te: "సింగిల్",
                price_paise: 19000,
                is_default: false,
                is_available: true,
            },
            {
                name: "Full (Serves 2)",
                name_te: "ఫుల్ (ఇద్దరికి)",
                price_paise: 26000,
                is_default: true,
                is_available: true,
            },
            {
                name: "Family Pack (Serves 4)",
                name_te: "ఫ్యామిలీ ప్యాక్ (నలుగురికి)",
                price_paise: 54000,
                is_default: false,
                is_available: true,
            },
            {
                name: "Jumbo Pack (Serves 6)",
                name_te: "జంబో ప్యాక్ (ఆరుగురికి)",
                price_paise: 79000,
                is_default: false,
                is_available: true,
            },
        ],
        addons: [
            {
                name: "Extra Biryani Rice",
                name_te: "ఎక్స్ట్రా బిర్యానీ రైస్",
                price_paise: 11000,
                is_available: true,
            },
            {
                name: "Extra Boiled Egg (1 pc)",
                name_te: "ఎక్స్ట్రా గుడ్డు",
                price_paise: 2000,
                is_available: true,
            },
            {
                name: "Extra Salan & Raita",
                name_te: "సాలన్ & రైతా",
                price_paise: 3000,
                is_available: true,
            },
        ],
    },
    {
        id: 2,
        category_id: 1,
        name: "Chicken Fry Piece Biryani (Andhra Special)",
        name_te: "చికెన్ ఫ్రై పీస్ బిర్యానీ",
        description: "Aromatic biryani rice layered with crispy Andhra-style roasted chicken fry pieces and caramelized onions.",
        price_paise: 28000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/chicken_fry_piece_biryani.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: true,
        has_variants: true,
        variants: [
            {
                name: "Single",
                name_te: "సింగిల్",
                price_paise: 20000,
                is_default: false,
                is_available: true,
            },
            {
                name: "Full",
                name_te: "ఫుల్",
                price_paise: 28000,
                is_default: true,
                is_available: true,
            },
            {
                name: "Family Pack",
                name_te: "ఫ్యామిలీ ప్యాక్",
                price_paise: 58000,
                is_default: false,
                is_available: true,
            },
        ],
    },
    {
        id: 3,
        category_id: 1,
        name: "Special Mutton Dum Biryani",
        name_te: "మటన్ దమ్ బిర్యానీ",
        description: "Juicy tender pieces of baby lamb marinated in authentic spices and dum-cooked with aged basmati rice.",
        price_paise: 36000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/special_mutton_dum_biryani.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: true,
        has_variants: true,
        variants: [
            {
                name: "Full",
                name_te: "ఫుల్",
                price_paise: 36000,
                is_default: true,
                is_available: true,
            },
            {
                name: "Family Pack",
                name_te: "ఫ్యామిలీ ప్యాక్",
                price_paise: 75000,
                is_default: false,
                is_available: true,
            },
        ],
    },
    {
        id: 4,
        category_id: 1,
        name: "Kaju Paneer Biryani",
        name_te: "కాజు పన్నీర్ బిర్యానీ",
        description: "Fragrant dum biryani rice tossed with roasted whole cashews (kaju) and soft malai paneer cubes.",
        price_paise: 25000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/kaju_paneer_biryani.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: true,
        variants: [
            {
                name: "Regular",
                name_te: "రెగ్యులర్",
                price_paise: 25000,
                is_default: true,
                is_available: true,
            },
            {
                name: "Family Pack",
                name_te: "ఫ్యామిలీ ప్యాక్",
                price_paise: 52000,
                is_default: false,
                is_available: true,
            },
        ],
    },
    {
        id: 5,
        category_id: 1,
        name: "Surya Special Veg Dum Biryani",
        name_te: "వెజ్ దమ్ బిర్యానీ",
        description: "Farm-fresh vegetables, green peas, and paneer cooked on dum with aromatic whole spices and saffron rice.",
        price_paise: 21000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/veg_dum_biryani.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 6,
        category_id: 1,
        name: "Egg Dum Biryani",
        name_te: "ఎగ్ దమ్ బిర్యానీ",
        description: "Golden shallow-fried boiled eggs spiced with masala, layered over aromatic Hyderabadi biryani rice.",
        price_paise: 22000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/egg_dum_biryani.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 7,
        category_id: 2,
        name: "Punjabi Chicken Curry (Chef Special)",
        name_te: "పంజాబీ చికెన్ కర్రీ",
        description: "Traditional North Indian Dhaba-style chicken simmered with freshly ground coriander, tomatoes, ginger, and desi ghee. Pairs perfectly with Butter Naan!",
        price_paise: 26000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/punjabi_chicken_curry.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: true,
        has_variants: false,
    },
    {
        id: 8,
        category_id: 2,
        name: "Butter Chicken (Murgh Makhani)",
        name_te: "బట్టర్ చికెన్",
        description: "Smoky char-grilled tandoori chicken cooked in a velvety tomato, cashew cream, and rich butter gravy.",
        price_paise: 27000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/butter_chicken.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: true,
        has_variants: false,
    },
    {
        id: 9,
        category_id: 2,
        name: "Kadai Chicken",
        name_te: "కడాయి చికెన్",
        description: "Tender chicken cooked with crunchy bell peppers, onions, and freshly roasted kadai spices.",
        price_paise: 25000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/kadai_chicken.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 10,
        category_id: 2,
        name: "Andhra Chicken Curry (Guntur Spiced)",
        name_te: "ఆంధ్రా చికెన్ కర్రీ",
        description: "Fiery Rayalaseema/Andhra style chicken curry with local red chillies, poppy seeds, and roasted coconut gravy.",
        price_paise: 24000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/andhra_chicken_curry.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 11,
        category_id: 2,
        name: "Paneer Butter Masala",
        name_te: "పన్నీర్ బట్టర్ మసాలా",
        description: "Rich and creamy cottage cheese cubes bathed in smooth butter and cashew tomato gravy with kasuri methi.",
        price_paise: 23000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/paneer_butter_masala.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: true,
        has_variants: false,
    },
    {
        id: 12,
        category_id: 2,
        name: "Kadai Paneer",
        name_te: "కడాయి పన్నీర్",
        description: "Cottage cheese cubes tossed with capsicum, diced onions, and freshly crushed spices in a rich gravy.",
        price_paise: 23000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/kadai_paneer.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 13,
        category_id: 2,
        name: "Kaju Tomato Curry",
        name_te: "కాజు టొమాటో కర్రీ",
        description: "Crispy whole cashews cooked in a flavorful rich sweet-and-tangy tomato gravy.",
        price_paise: 25000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/kaju_tomato_curry.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 14,
        category_id: 2,
        name: "Dal Tadka (Desi Ghee)",
        name_te: "దాల్ తడ్కా",
        description: "Yellow toor dal tempered with cumin, garlic, red chillies, and aromatic pure desi ghee.",
        price_paise: 16000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/dal_tadka.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 15,
        category_id: 2,
        name: "Mushroom Masala",
        name_te: "మష్రూమ్ మసాలా",
        description: "Button mushrooms cooked in an onion-tomato spicy masala with whole aromatic herbs.",
        price_paise: 22000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/mushroom_masala.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 16,
        category_id: 3,
        name: "Tandoori Chicken (Full / Half)",
        name_te: "తందూరి చికెన్",
        description: "Whole chicken marinated overnight in Kashmiri chilli, spiced hung curd, and roasted over clay charcoal tandoor.",
        price_paise: 26000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/tandoori_chicken.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: true,
        has_variants: true,
        variants: [
            {
                name: "Half (2 Pcs)",
                name_te: "హాఫ్ (2 ముక్కలు)",
                price_paise: 26000,
                is_default: true,
                is_available: true,
            },
            {
                name: "Full (4 Pcs)",
                name_te: "ఫుల్ (4 ముక్కలు)",
                price_paise: 48000,
                is_default: false,
                is_available: true,
            },
        ],
    },
    {
        id: 17,
        category_id: 3,
        name: "Chicken Tikka (6 Pcs)",
        name_te: "చికెన్ టిక్కా (6)",
        description: "Boneless chicken chunks marinated in mustard oil, ajwain, and tandoori spices, char-grilled to perfection.",
        price_paise: 25000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/chicken_tikka.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 18,
        category_id: 3,
        name: "Tangdi Kebab (3 Pcs)",
        name_te: "టాంగ్డి కబాబ్ (3)",
        description: "Chicken drumsticks stuffed with cheese and spices, roasted golden in charcoal tandoor.",
        price_paise: 26000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/tangdi_kebab.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 19,
        category_id: 3,
        name: "Paneer Tikka (6 Pcs)",
        name_te: "పన్నీర్ టిక్కా (6)",
        description: "Juicy chunks of malai paneer and crunchy peppers marinated in tandoori masala and grilled on skewers.",
        price_paise: 22000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/paneer_tikka.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 20,
        category_id: 4,
        name: "Chicken Lollipop (Saucy / Dry)",
        name_te: "చికెన్ లాలిపాప్ (6)",
        description: "Crispy seasoned chicken winglets served crispy dry or tossed in spicy Indo-Chinese garlic sauce.",
        price_paise: 24000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/chicken_lollipop.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: true,
        has_variants: false,
    },
    {
        id: 21,
        category_id: 4,
        name: "Chilli Chicken",
        name_te: "చిల్లీ చికెన్",
        description: "Crispy boneless chicken tossed with green chillies, onions, garlic, and dark soy sauce.",
        price_paise: 24000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/chilli_chicken.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 22,
        category_id: 4,
        name: "Dragon Chicken",
        name_te: "డ్రాగన్ చికెన్",
        description: "Crispy chicken strips tossed in spicy sweet chili sauce, roasted cashews, and sesame seeds.",
        price_paise: 25000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/dragon_chicken.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 23,
        category_id: 4,
        name: "Apollo Fish",
        name_te: "అపోలో ఫిష్",
        description: "Hyderabadi style boneless fish fillets spiced with curry leaves, yogurt, green chillies, and spices.",
        price_paise: 28000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/apollo_fish.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 24,
        category_id: 4,
        name: "Guntur Chicken Dry",
        name_te: "గుంటూరు చికెన్ ఫ్రై",
        description: "Traditional spicy dry roasted chicken infused with Guntur red chillies and curry leaves.",
        price_paise: 25000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/guntur_chicken_dry.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 25,
        category_id: 5,
        name: "Crispy Corn Pepper Salt",
        name_te: "క్రిస్పీ కార్న్",
        description: "Golden fried American sweet corn tossed with freshly cracked black pepper, capsicum, and spring onions.",
        price_paise: 18000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/crispy_corn.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: true,
        has_variants: false,
    },
    {
        id: 26,
        category_id: 5,
        name: "Veg Manchurian (Dry)",
        name_te: "వెజ్ మంచూరియా",
        description: "Crispy vegetable dumplings tossed with ginger, garlic, chopped onions, and Indo-Chinese sauces.",
        price_paise: 17000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/veg_manchurian.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 27,
        category_id: 5,
        name: "Chilli Paneer (Dry)",
        name_te: "చిల్లీ పన్నీర్",
        description: "Batter-fried paneer cubes wok-tossed with capsicum, garlic, spring onions, and green chillies.",
        price_paise: 21000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/chilly_paneer.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 28,
        category_id: 5,
        name: "Gobi 65",
        name_te: "గోబీ 65",
        description: "Crispy spiced cauliflower florets tossed with curry leaves, crushed pepper, and lemon juice.",
        price_paise: 16000,
        is_veg: true,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/gobi_65.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 29,
        category_id: 6,
        name: "Butter Naan",
        name_te: "బట్టర్ నాన్",
        description: "Soft, fluffy clay-oven leavened bread brushed generously with melting butter.",
        price_paise: 5000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/butter_naan.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: true,
        has_variants: false,
    },
    {
        id: 30,
        category_id: 6,
        name: "Garlic Butter Naan",
        name_te: "గార్లిక్ బట్టర్ నాన్",
        description: "Tandoori naan topped with roasted garlic flakes, fresh coriander, and melted butter.",
        price_paise: 6500,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/garlic_butter_naan.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: true,
        has_variants: false,
    },
    {
        id: 31,
        category_id: 6,
        name: "Tandoori Roti (Butter)",
        name_te: "తందూరి రోటీ (బట్టర్)",
        description: "Whole wheat bread baked in clay tandoor and brushed with fresh butter.",
        price_paise: 3000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/tandoori_roti_butter.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 32,
        category_id: 6,
        name: "Tandoori Roti (Plain)",
        name_te: "తందూరి రోటీ (ప్లెయిన్)",
        description: "Crisp and healthy traditional whole wheat roti baked in charcoal tandoor.",
        price_paise: 2500,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/tandoori_roti_plain.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 33,
        category_id: 6,
        name: "Rumali Roti",
        name_te: "రుమాలి రోటీ",
        description: "Hand-tossed ultra-thin, soft handkerchief-style Indian bread.",
        price_paise: 3500,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/rumali_roti.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 34,
        category_id: 7,
        name: "Surya Special Chicken Fried Rice",
        name_te: "స్పెషల్ చికెన్ ఫ్రైడ్ రైస్",
        description: "Wok-tossed basmati rice with shredded chicken, scramble egg, crunchy veggies, and chef's special seasoning.",
        price_paise: 21000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/chicken_fried_rice.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 35,
        category_id: 7,
        name: "Schezwan Chicken Fried Rice",
        name_te: "షెజ్వాన్ చికెన్ ఫ్రైడ్ రైస్",
        description: "Spicy wok-fried rice tossed with fiery Schezwan sauce, chicken, and spring onions.",
        price_paise: 22000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/schezwan_chicken_fried_rice.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 36,
        category_id: 7,
        name: "Veg Fried Rice",
        name_te: "వెజ్ ఫ్రైడ్ రైస్",
        description: "Classic wok-tossed rice with finely chopped carrots, beans, cabbage, and light soy sauce.",
        price_paise: 17000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/veg_fried_rice.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 37,
        category_id: 7,
        name: "Chicken Hakka Noodles",
        name_te: "చికెన్ హక్కా నూడుల్స్",
        description: "Stir-fried noodles with shredded chicken, crisp cabbage, capsicum, and oriental spices.",
        price_paise: 21000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/chicken_hakka_noodles.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 38,
        category_id: 7,
        name: "Veg Hakka Noodles",
        name_te: "వెజ్ హక్కా నూడుల్స్",
        description: "Street-style stir-fried wheat noodles with garden fresh vegetables and mild spices.",
        price_paise: 17000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/veg_hakka_noodles.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 39,
        category_id: 8,
        name: "Chicken Manchow Soup",
        name_te: "చికెన్ మంచోవ్ సూప్",
        description: "Hearty Indo-Chinese spiced soup with chicken and egg, topped with crispy fried noodles.",
        price_paise: 13000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/chicken_manchow_soup.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 40,
        category_id: 8,
        name: "Sweet Corn Chicken Soup",
        name_te: "స్వీట్ కార్న్ చికెన్ సూప్",
        description: "Comforting creamy sweet corn soup with tender chicken shreds and egg drops.",
        price_paise: 13000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/chicken_sweet_corn_soup.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 41,
        category_id: 8,
        name: "Cream of Tomato Soup",
        name_te: "టొమాటో సూప్",
        description: "Silky smooth ripe tomato soup with butter, herbs, and crispy golden croutons.",
        price_paise: 11000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/cream_of_tomato_soup.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 42,
        category_id: 9,
        name: "Curd Rice (Bagala Bath)",
        name_te: "పెరుగు అన్నం",
        description: "Cooling and creamy tempered homemade curd rice with mustard, ginger, green chillies, and pomegranate.",
        price_paise: 10000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/curd_rice_bagala_bath.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: true,
        has_variants: false,
    },
    {
        id: 43,
        category_id: 9,
        name: "Jeera Rice",
        name_te: "జీరా రైస్",
        description: "Fragrant long-grain basmati rice tempered with roasted cumin seeds and fresh coriander in pure ghee.",
        price_paise: 14000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/jeera_rice.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 44,
        category_id: 10,
        name: "Fresh Lime Soda (Sweet / Salt)",
        name_te: "లెమన్ సోడా",
        description: "Refreshing fizzy soda infused with freshly squeezed Kadiri lemon juice and mint.",
        price_paise: 5000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/fresh_lime_soda.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 45,
        category_id: 10,
        name: "Sweet Lassi (Chilled)",
        name_te: "స్వీట్ లస్సీ",
        description: "Thick whipped sweet yogurt lassi topped with malai and cardamom essence.",
        price_paise: 6000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/sweet_lassi.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
    {
        id: 46,
        category_id: 10,
        name: "Gulab Jamun with Vanilla Ice Cream (2 Pcs)",
        name_te: "గులాబ్ జామూన్ విత్ ఐస్ క్రీం",
        description: "Warm, melt-in-the-mouth mawa gulab jamuns served alongside a scoop of rich vanilla ice cream.",
        price_paise: 9000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/gulab_jamun_icecream.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: true,
        has_variants: false,
    },
    {
        id: 47,
        category_id: 10,
        name: "Apricot Delight (Surya Special)",
        name_te: "ఆప్రికాట్ డిలైట్",
        description: "Rich layered dessert made of stewed Turkish apricots, sponge cake, and thick fresh cream.",
        price_paise: 12000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/apricot_delight.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: true,
        has_variants: false,
    },
    {
        id: 48,
        category_id: 10,
        name: "Thums Up / Soft Drinks (750ml)",
        name_te: "కూల్ డ్రింక్",
        description: "Chilled beverage bottle.",
        price_paise: 4500,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/thums_up_beverage.jpg",
        is_available: true,
        track_stock: true,
        stock_qty: 100,
        low_stock_threshold: 15,
        is_special: false,
        has_variants: false,
    },
];
