/**
 * Surya Family Restaurant Kadiri — Authentic Menu Dataset
 * Dhandubatu Street, Bypass Road, Opp. RTC Bus Stand, Kadiri, Andhra Pradesh
 * Phone: +91 98803 58634 | UPI: 9880358634@upi
 */

export interface StaticMenuItem {
    id: number;
    category_id: number;
    name: string;
    name_te: string;
    description: string;
    price_paise: number;
    is_veg: boolean;
    is_spicy: boolean;
    is_best_seller: boolean;
    image_url: string;
}

export interface StaticCategory {
    id: number;
    name: string;
    name_te: string;
    icon: string;
    image_url: string;
}

export const SURYA_CATEGORIES: StaticCategory[] = [
    {
        id: 1,
        name: "Biryani & Pulao Specials",
        name_te: "బిర్యానీ & పులావ్ స్పెషల్స్",
        icon: "Flame",
        image_url: "/dishes/3d_biryani.jpg",
    },
    {
        id: 2,
        name: "Punjabi & North Indian Curries",
        name_te: "పంజాబీ & నార్త్ ఇండియన్ కూరలు",
        icon: "UtensilsCrossed",
        image_url: "/dishes/3d_curries.jpg",
    },
    {
        id: 3,
        name: "Tandoori & Kebabs",
        name_te: "తందూరి & కబాబ్స్",
        icon: "Flame",
        image_url: "/dishes/3d_nonveg_starters.jpg",
    },
    {
        id: 4,
        name: "Non-Veg Starters & Andhra Specials",
        name_te: "నాన్-వెజ్ స్టార్టర్స్ & ఆంధ్రా స్పెషల్స్",
        icon: "Flame",
        image_url: "/dishes/chicken_lollipop.jpg",
    },
    {
        id: 5,
        name: "Veg Starters & Crispies",
        name_te: "వెజ్ స్టార్టర్స్ & క్రిస్పీస్",
        icon: "Salad",
        image_url: "/dishes/3d_veg_starters.jpg",
    },
    {
        id: 6,
        name: "Indian Breads & Naans",
        name_te: "రొట్టెలు, నాన్స్ & కుల్చా",
        icon: "CircleDot",
        image_url: "/dishes/3d_curries.jpg",
    },
    {
        id: 7,
        name: "Arabic Mandi Specials",
        name_te: "అరేబిక్ మండి స్పెషల్స్",
        icon: "Crown",
        image_url: "/dishes/3d_mandi.jpg",
    },
    {
        id: 8,
        name: "Chinese Rice & Noodles",
        name_te: "చైనీస్ రైస్ & నూడుల్స్",
        icon: "Soup",
        image_url: "/dishes/chilly_chicken_dry.jpg",
    },
    {
        id: 9,
        name: "Desserts & Sweets",
        name_te: "స్వీట్లు & డెజర్ట్స్",
        icon: "Sparkles",
        image_url: "/dishes/double_ka_meetha.jpg",
    },
    {
        id: 10,
        name: "Beverages & Lassi",
        name_te: "కూల్ డ్రింక్స్ & లస్సీ",
        icon: "Coffee",
        image_url: "/dishes/3d_beverages.jpg",
    },
];

export const SURYA_MENU_ITEMS: StaticMenuItem[] = [
    // Biryani & Pulao
    {
        id: 101,
        category_id: 1,
        name: "Surya Special Chicken Dum Biryani",
        name_te: "సూర్య స్పెషల్ చికెన్ దమ్ బిర్యానీ",
        description: "Fragrant long-grain basmati rice slow-cooked with tender marinated chicken, saffron, ghee, fried onions, and signature Kadiri spices. Served with rich mirchi ka salan and dahi raita.",
        price_paise: 26000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/3d_biryani.jpg",
    },
    {
        id: 102,
        category_id: 1,
        name: "Mutton Dum Biryani",
        name_te: "మటన్ దమ్ బిర్యానీ",
        description: "Tender goat meat slow-cooked to bone-soft perfection layered in aromatic spiced basmati rice. Served with mint raita.",
        price_paise: 38000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/3d_biryani.jpg",
    },
    {
        id: 103,
        category_id: 1,
        name: "Chicken Fry Piece Biryani",
        name_te: "చికెన్ ఫ్రై పీస్ బిర్యానీ",
        description: "Crispy fried Andhra chicken pieces laid generously over flavorful dum-infused biryani rice.",
        price_paise: 28000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/3d_biryani.jpg",
    },
    {
        id: 104,
        category_id: 1,
        name: "Chicken Lollipop Biryani",
        name_te: "చికెన్ లాలీపాప్ బిర్యానీ",
        description: "Crispy spiced chicken wingettes layered over piping hot fragrant biryani rice. A Kadiri customer favorite!",
        price_paise: 30000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/chicken_lollipop.jpg",
    },
    {
        id: 105,
        category_id: 1,
        name: "Paneer Tikka Dum Biryani",
        name_te: "పన్నీర్ టిక్కా దమ్ బిర్యానీ",
        description: "Chargrilled cottage cheese cubes in rich tandoori spices layered in fragrant basmati rice.",
        price_paise: 23000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/paneer_butter_masala.jpg",
    },
    {
        id: 106,
        category_id: 1,
        name: "Kaju Mushroom Biryani",
        name_te: "జీడిపప్పు మష్రూమ్ బిర్యానీ",
        description: "Fresh button mushrooms and golden roasted cashews cooked with aromatic biryani spices.",
        price_paise: 24000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/kaju_paneer.jpg",
    },
    {
        id: 107,
        category_id: 1,
        name: "Kaju Chicken Pulao (Special)",
        name_te: "స్పెషల్ కాజు చికెన్ పులావ్",
        description: "Ghee-tossed mild basmati pulao topped with plenty of roasted whole cashews and tender chicken pieces.",
        price_paise: 32000,
        is_veg: false,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/3d_biryani.jpg",
    },

    // Curries
    {
        id: 201,
        category_id: 2,
        name: "Punjabi Chicken Curry",
        name_te: "పంజాబీ చికెన్ కర్రీ",
        description: "Classic rich tomato-onion-cashew gravy simmered with rustic whole spices, tender chicken, and fresh coriander.",
        price_paise: 24000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/3d_curries.jpg",
    },
    {
        id: 202,
        category_id: 2,
        name: "Butter Chicken (Murgh Makhani)",
        name_te: "బట్టర్ చికెన్",
        description: "Smoky tandoori chicken tikka chunks cooked in a velvety, buttery makhani sauce infused with fenugreek.",
        price_paise: 26000,
        is_veg: false,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/butter_chicken.jpg",
    },
    {
        id: 203,
        category_id: 2,
        name: "Kadiri Andhra Chicken Curry (Natu Kodi Style)",
        name_te: "ఆంధ్రా చికెన్ కూర",
        description: "Spicy and tangy Rayalaseema home-style chicken curry with roasted ground spices, poppy seeds, and red chillies.",
        price_paise: 25000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/3d_curries.jpg",
    },
    {
        id: 204,
        category_id: 2,
        name: "Mutton Rogan Josh",
        name_te: "మటన్ రోగన్ జోష్",
        description: "Kashmiri style aromatic goat curry slow-braised with ratan jot, fennel, dry ginger, and spiced curd gravy.",
        price_paise: 38000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/mutton_curry.jpg",
    },
    {
        id: 205,
        category_id: 2,
        name: "Paneer Butter Masala",
        name_te: "పన్నీర్ బట్టర్ మసాలా",
        description: "Tender cubes of fresh paneer simmered in a luscious sweet-tangy cream and butter tomato sauce.",
        price_paise: 21000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/paneer_butter_masala.jpg",
    },
    {
        id: 206,
        category_id: 2,
        name: "Kadai Paneer",
        name_te: "కడాయి పన్నీర్",
        description: "Paneer and crunchy bell peppers tossed in a rustic freshly ground coriander-chilli kadai masala.",
        price_paise: 22000,
        is_veg: true,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/paneer_butter_masala.jpg",
    },
    {
        id: 207,
        category_id: 2,
        name: "Kaju Paneer Masala",
        name_te: "కాజు పన్నీర్ మసాలా",
        description: "Royal cashew paste gravy loaded with roasted cashews and soft paneer cubes.",
        price_paise: 25000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/kaju_paneer.jpg",
    },
    {
        id: 208,
        category_id: 2,
        name: "Dal Tadka (Desi Ghee)",
        name_te: "దేశీ నెయ్యి దాల్ తడ్కా",
        description: "Yellow toor dal tempered with cumin, garlic, dry red chillies, and aromatic pure desi cow ghee.",
        price_paise: 15000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/dal_tadka.jpg",
    },

    // Tandoori & Kebabs
    {
        id: 301,
        category_id: 3,
        name: "Tandoori Chicken (Full)",
        name_te: "తందూరి చికెన్ (ఫుల్)",
        description: "Whole whole spring chicken marinated overnight in hung curd and tandoori spices, char-roasted in clay oven.",
        price_paise: 46000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/tandoori_chicken.jpg",
    },
    {
        id: 302,
        category_id: 3,
        name: "Tandoori Chicken (Half)",
        name_te: "తందూరి చికెన్ (హాఫ్)",
        description: "Half spring chicken roasted over glowing charcoal with lemon and chaat masala. Served with green chutney.",
        price_paise: 24000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/tandoori_chicken.jpg",
    },
    {
        id: 303,
        category_id: 3,
        name: "Chicken Tikka (6 Pcs)",
        name_te: "చికెన్ టిక్కా",
        description: "Boneless chicken morsels grilled on skewers with charred bell peppers and spicy marinade.",
        price_paise: 24000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/chicken_tikka.jpg",
    },
    {
        id: 304,
        category_id: 3,
        name: "Chicken Malai Tikka (Melt-in-Mouth)",
        name_te: "చికెన్ మలై టిక్కా",
        description: "Mild, creamy chicken skewers marinated in cashew paste, cheese, cardamom, and fresh dairy cream.",
        price_paise: 26000,
        is_veg: false,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/chicken_tikka.jpg",
    },
    {
        id: 305,
        category_id: 3,
        name: "Paneer Tikka (Tandoori)",
        name_te: "పన్నీర్ టిక్కా",
        description: "Thick fresh cottage cheese slices with capsicum and onions grilled in hot clay tandoor.",
        price_paise: 22000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/paneer_tikka.jpg",
    },

    // Non-Veg Starters
    {
        id: 401,
        category_id: 4,
        name: "Surya Special Chicken 65",
        name_te: "సూర్య స్పెషల్ చికెన్ 65",
        description: "Kadiri style deep-fried boneless chicken tossed with curry leaves, crushed garlic, and spicy green chillies.",
        price_paise: 22000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/chicken_65.jpg",
    },
    {
        id: 402,
        category_id: 4,
        name: "Chicken Lollipop (Dry, 6 Pcs)",
        name_te: "చికెన్ లాలీపాప్",
        description: "French-trimmed chicken wing drums coated in crisp Indo-Chinese batter with spicy garlic dip.",
        price_paise: 24000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/chicken_lollipop.jpg",
    },
    {
        id: 403,
        category_id: 4,
        name: "Chilly Chicken (Andhra Dry)",
        name_te: "చిల్లీ చికెన్ డ్రై",
        description: "Wok-tossed chicken chunks with green chillies, soy, cracked black pepper, and fresh scallions.",
        price_paise: 23000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/chilly_chicken_dry.jpg",
    },
    {
        id: 404,
        category_id: 4,
        name: "Dragon Chicken",
        name_te: "డ్రాగన్ చికెన్",
        description: "Crispy batter strips tossed in sweet-and-fiery red sauce, cashew nuts, and roasted sesame.",
        price_paise: 25000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/dragon_chicken.jpg",
    },
    {
        id: 405,
        category_id: 4,
        name: "Apollo Fish",
        name_te: "అపోలో ఫిష్",
        description: "Boneless fish fillets cut into finger strips, seasoned with curd, turmeric, curry leaves, and green chillies.",
        price_paise: 28000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/apollo_fish.jpg",
    },
    {
        id: 406,
        category_id: 4,
        name: "Mutton Pepper Fry (Sukka)",
        name_te: "మటన్ పెప్పర్ ఫ్రై",
        description: "Slow roasted tender mutton cubes cooked in thick black pepper, curry leaves, and caramelized shallots.",
        price_paise: 36000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/mutton_pepper_fry.jpg",
    },

    // Veg Starters
    {
        id: 501,
        category_id: 5,
        name: "Gobi Manchurian (Crispy Dry)",
        name_te: "గోబీ మంచూరియన్",
        description: "Batter-fried crunchy cauliflower florets tossed in zesty garlic, soy, ginger, and spring onions.",
        price_paise: 16000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/gobi_manchurian.jpg",
    },
    {
        id: 502,
        category_id: 5,
        name: "Chilli Paneer (Dry)",
        name_te: "చిల్లీ పన్నీర్",
        description: "Crisp cottage cheese cubes with onions, capsicum, and spicy Indo-Chinese chilli glaze.",
        price_paise: 19000,
        is_veg: true,
        is_spicy: true,
        is_best_seller: true,
        image_url: "/dishes/chilly_paneer.jpg",
    },
    {
        id: 503,
        category_id: 5,
        name: "Baby Corn 65",
        name_te: "బేబీ కార్న్ 65",
        description: "Golden fried tender baby corn fingers with crunchy curry leaves and South Indian spices.",
        price_paise: 17000,
        is_veg: true,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/babycorn_65.jpg",
    },
    {
        id: 504,
        category_id: 5,
        name: "Crispy Veg Spring Rolls (4 Pcs)",
        name_te: "వెజ్ స్ప్రింగ్ రోల్స్",
        description: "Delicate pastry rolls stuffed with finely shredded cabbage, carrots, and glass noodles. Served with sweet chilli dip.",
        price_paise: 16000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/spring_roll.jpg",
    },

    // Indian Breads
    {
        id: 601,
        category_id: 6,
        name: "Butter Naan",
        name_te: "బట్టర్ నాన్",
        description: "Traditional refined flour flatbread baked in clay oven and brushed with generous amul butter.",
        price_paise: 4000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/3d_curries.jpg",
    },
    {
        id: 602,
        category_id: 6,
        name: "Garlic Butter Naan",
        name_te: "గార్లిక్ బట్టర్ నాన్",
        description: "Clay oven baked naan topped with crushed roasted garlic cloves, fresh coriander, and melted butter.",
        price_paise: 5500,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/3d_curries.jpg",
    },
    {
        id: 603,
        category_id: 6,
        name: "Tandoori Roti (Butter)",
        name_te: "తందూరి రోటీ (బట్టర్)",
        description: "Healthy whole wheat flour bread baked in tandoor with pure amul butter.",
        price_paise: 3000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/3d_curries.jpg",
    },
    {
        id: 604,
        category_id: 6,
        name: "Rumali Roti",
        name_te: "రుమాలి రోటీ",
        description: "Paper-thin handkerchief bread cooked over inverted kadai, soft and fold-friendly.",
        price_paise: 3500,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/3d_curries.jpg",
    },

    // Arabic Mandi
    {
        id: 701,
        category_id: 7,
        name: "Chicken Mandi (Half - 2 Persons)",
        name_te: "చికెన్ మండి (హాఫ్)",
        description: "Smoky Arabic spiced mandi rice served on wide platter with tender juicy roasted chicken, dry fruits, and red chilli tomato salsa.",
        price_paise: 44000,
        is_veg: false,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/3d_mandi.jpg",
    },
    {
        id: 702,
        category_id: 7,
        name: "Mutton Mandi (Half - 2 Persons)",
        name_te: "మటన్ మండి (హాఫ్)",
        description: "Arabic spiced basmati rice cooked in rich meat broth, topped with fall-apart braised lamb shank, fried nuts, and mandi soup.",
        price_paise: 65000,
        is_veg: false,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/3d_mandi.jpg",
    },

    // Chinese
    {
        id: 801,
        category_id: 8,
        name: "Chicken Fried Rice",
        name_te: "చికెన్ ఫ్రైడ్ రైస్",
        description: "Stir-fried long grain rice with tender chicken cubes, scrambled egg, scallions, and soy seasonings.",
        price_paise: 19000,
        is_veg: false,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/chilly_chicken_dry.jpg",
    },
    {
        id: 802,
        category_id: 8,
        name: "Schezwan Chicken Noodles",
        name_te: "షెజ్వాన్ చికెన్ నూడుల్స్",
        description: "Fiery wok-tossed hakka noodles with chicken slices in hot red Schezwan pepper sauce.",
        price_paise: 21000,
        is_veg: false,
        is_spicy: true,
        is_best_seller: false,
        image_url: "/dishes/chilly_chicken_dry.jpg",
    },
    {
        id: 803,
        category_id: 8,
        name: "Veg Hakka Fried Rice",
        name_te: "వెజ్ ఫ్రైడ్ రైస్",
        description: "Wok tossed garden vegetables, carrot, beans, and spring onion fried rice.",
        price_paise: 16000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/chilly_gobi.jpg",
    },

    // Desserts
    {
        id: 901,
        category_id: 9,
        name: "Hyderabadi Double Ka Meetha",
        name_te: "డబుల్ కా మీఠా",
        description: "Decadent fried bread pudding soaked in saffron-infused rabri milk, topped with sliced almonds and pistachios.",
        price_paise: 12000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/double_ka_meetha.jpg",
    },
    {
        id: 902,
        category_id: 9,
        name: "Gulab Jamun (Hot with Rabri, 2 Pcs)",
        name_te: "గులాబ్ జామున్",
        description: "Mawa dumplings fried to golden brown, soaked in rose cardamom sugar syrup, served piping hot with rabri.",
        price_paise: 10000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/gulab_jamun.jpg",
    },
    {
        id: 903,
        category_id: 9,
        name: "Gajar Ka Halwa (Pure Desi Ghee)",
        name_te: "గాజర్ కా హల్వా",
        description: "Grated red Delhi carrots slow-roasted in desi cow ghee, reduced milk khoya, and crunchy cashews.",
        price_paise: 13000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/gajar_ka_halwa.jpg",
    },

    // Beverages
    {
        id: 1001,
        category_id: 10,
        name: "Special Sweet Punjabi Lassi",
        name_te: "పంజాబీ స్వీట్ లస్సీ",
        description: "Thick hand-churned fresh curd lassi topped with fresh malai layer and slivered pistachios.",
        price_paise: 7000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/3d_beverages.jpg",
    },
    {
        id: 1002,
        category_id: 10,
        name: "Fresh Lime Soda (Sweet / Salt)",
        name_te: "లెమన్ సోడా",
        description: "Chilled effervescent soda with fresh Kadiri lime juice, mint, and rock salt.",
        price_paise: 5000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: false,
        image_url: "/dishes/3d_beverages.jpg",
    },
    {
        id: 1003,
        category_id: 10,
        name: "Masala Spiced Buttermilk (Chaas)",
        name_te: "మసాలా మజ్జిగ",
        description: "Refreshing spiced buttermilk infused with crushed ginger, green chilli, roasted cumin, and curry leaves.",
        price_paise: 4000,
        is_veg: true,
        is_spicy: false,
        is_best_seller: true,
        image_url: "/dishes/3d_beverages.jpg",
    },
];
